"""multi_area_reports_roof_type_defaults_advance_due_date

Revision ID: 06299a5101f5
Revises: 9e3bb642c686
Create Date: 2026-09-10 10:07:31.033494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06299a5101f5'
down_revision = '9e3bb642c686'
branch_labels = None
depends_on = None


def _resolve_roof_type_default_template_rows(bind):
    """Ermittelt für jeden bestehenden, tatsächlich verwendeten roof_type genau die
    InspectionTemplate, die HEUTE (vor dieser Migration) über die bisherige implizite
    Auflösung in _resolve_inspection_template() gewinnen würde -- niedrigster sort_order, dann
    niedrigste id, unter den nicht archivierten Vorlagen mit genau diesem roof_type. Damit
    verhält sich eine bestehende Installation am Tag der Migration identisch weiter, nur ist
    die Zuordnung jetzt explizit sichtbar/änderbar (Einstellungen -> Prüfvorlagen). Ein
    roof_type, für den ausschließlich archivierte Vorlagen existieren, wird bewusst
    NICHT bestückt -- vorher fiel die Auflösung für ihn ebenfalls auf die roof_type IS
    NULL-Stufe zurück, das bleibt unverändert. Modulweite Funktion (nicht in upgrade()
    verschachtelt), damit ein Test sie direkt gegen eine präparierte Verbindung aufrufen kann
    (Muster aus 4609e3fc8976::_resolve_roof_component_type_rows)."""
    roof_types = [
        row[0] for row in bind.execute(
            sa.text("SELECT DISTINCT roof_type FROM inspection_templates WHERE roof_type IS NOT NULL")
        ).fetchall()
    ]
    rows = []
    for roof_type in roof_types:
        winner_id = bind.execute(
            sa.text(
                "SELECT id FROM inspection_templates WHERE roof_type = :rt AND archived = 0 "
                "ORDER BY sort_order, id LIMIT 1"
            ),
            {"rt": roof_type},
        ).scalar()
        if winner_id is not None:
            rows.append((roof_type, winner_id))
    return rows


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roof_type_inspection_template_defaults',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roof_type', sa.String(length=80), nullable=False),
    sa.Column('inspection_template_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['inspection_template_id'], ['inspection_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roof_type_inspection_template_defaults', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roof_type_inspection_template_defaults_roof_type'), ['roof_type'], unique=True)

    op.create_table('service_report_roof_areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_report_id', sa.Integer(), nullable=False),
    sa.Column('roof_area_id', sa.Integer(), nullable=False),
    sa.Column('inspection_template_id', sa.Integer(), nullable=True),
    sa.Column('inspection_template_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['inspection_template_id'], ['inspection_templates.id'], ),
    sa.ForeignKeyConstraint(['roof_area_id'], ['roof_areas.id'], ),
    sa.ForeignKeyConstraint(['service_report_id'], ['service_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service_report_roof_areas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_report_roof_areas_roof_area_id'), ['roof_area_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_report_roof_areas_service_report_id'), ['service_report_id'], unique=False)

    with op.batch_alter_table('inspection_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('roof_area_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_inspection_items_roof_area_id'), ['roof_area_id'], unique=False)
        batch_op.create_foreign_key('fk_inspection_items_roof_area_id', 'roof_areas', ['roof_area_id'], ['id'])

    with op.batch_alter_table('service_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('advance_due_date_on_sign', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###

    # Datenmigration: bestehende, implizite Dachtyp-Standardvorlage explizit übernehmen (siehe
    # _resolve_roof_type_default_template_rows() oben).
    bind = op.get_bind()
    defaults_table = sa.table(
        'roof_type_inspection_template_defaults',
        sa.column('roof_type', sa.String), sa.column('inspection_template_id', sa.Integer),
    )
    seed_rows = _resolve_roof_type_default_template_rows(bind)
    if seed_rows:
        op.bulk_insert(defaults_table, [
            {'roof_type': roof_type, 'inspection_template_id': template_id}
            for roof_type, template_id in seed_rows
        ])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_reports', schema=None) as batch_op:
        batch_op.drop_column('advance_due_date_on_sign')

    with op.batch_alter_table('inspection_items', schema=None) as batch_op:
        batch_op.drop_constraint('fk_inspection_items_roof_area_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_inspection_items_roof_area_id'))
        batch_op.drop_column('roof_area_id')

    with op.batch_alter_table('service_report_roof_areas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_report_roof_areas_service_report_id'))
        batch_op.drop_index(batch_op.f('ix_service_report_roof_areas_roof_area_id'))

    op.drop_table('service_report_roof_areas')
    with op.batch_alter_table('roof_type_inspection_template_defaults', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roof_type_inspection_template_defaults_roof_type'))

    op.drop_table('roof_type_inspection_template_defaults')
    # ### end Alembic commands ###
