"""Mahnwesen: reminder_levels und reminders

Revision ID: 0946c1a4c4be
Revises: bb175f455b64
Create Date: 2026-09-04 15:37:31.244846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0946c1a4c4be'
down_revision = 'bb175f455b64'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminder_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('days_after_previous_step', sa.Integer(), nullable=False),
    sa.Column('fee_amount', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('text_template', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reminder_levels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reminder_levels_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_reminder_levels_level'), ['level'], unique=False)

    op.create_table('reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reminder_number', sa.String(length=50), nullable=True),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reminder_date', sa.Date(), nullable=False),
    sa.Column('new_due_date', sa.Date(), nullable=True),
    sa.Column('outstanding_amount', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('fee_amount', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reminders_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reminders_level'), ['level'], unique=False)
        batch_op.create_index(batch_op.f('ix_reminders_reminder_number'), ['reminder_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_reminders_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reminders_status'))
        batch_op.drop_index(batch_op.f('ix_reminders_reminder_number'))
        batch_op.drop_index(batch_op.f('ix_reminders_level'))
        batch_op.drop_index(batch_op.f('ix_reminders_invoice_id'))

    op.drop_table('reminders')
    with op.batch_alter_table('reminder_levels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reminder_levels_level'))
        batch_op.drop_index(batch_op.f('ix_reminder_levels_active'))

    op.drop_table('reminder_levels')
    # ### end Alembic commands ###
