"""inspection templates und items

Revision ID: 09b654357a58
Revises: 623c88dc1bae
Create Date: 2026-09-09 12:08:32.852053

"""
from datetime import datetime

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09b654357a58'
down_revision = '623c88dc1bae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inspection_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('roof_type', sa.String(length=80), nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='100', nullable=False),
    sa.Column('archived', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inspection_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inspection_templates_archived'), ['archived'], unique=False)

    op.create_table('inspection_template_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='100', nullable=False),
    sa.Column('group_name', sa.String(length=120), nullable=True),
    sa.Column('component_type', sa.String(length=80), nullable=True),
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('item_type', sa.String(length=30), nullable=False),
    sa.Column('required', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('target_min', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('target_max', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('photo_required', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('photo_before_after', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['inspection_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inspection_template_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inspection_template_items_template_id'), ['template_id'], unique=False)

    op.create_table('inspection_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_report_id', sa.Integer(), nullable=False),
    sa.Column('template_item_id', sa.Integer(), nullable=True),
    sa.Column('roof_component_id', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=120), nullable=True),
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('item_type', sa.String(length=30), nullable=False),
    sa.Column('required', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('target_min', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('target_max', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('photo_required', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('photo_before_after', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('result', sa.String(length=20), nullable=True),
    sa.Column('condition_grade', sa.Integer(), nullable=True),
    sa.Column('measured_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.Column('recorded_by_employee_id', sa.Integer(), nullable=True),
    sa.Column('client_uuid', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recorded_by_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['roof_component_id'], ['roof_components.id'], ),
    sa.ForeignKeyConstraint(['service_report_id'], ['service_reports.id'], ),
    sa.ForeignKeyConstraint(['template_item_id'], ['inspection_template_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_report_id', 'client_uuid', name='uq_inspection_item_client_uuid')
    )
    with op.batch_alter_table('inspection_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inspection_items_client_uuid'), ['client_uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_inspection_items_service_report_id'), ['service_report_id'], unique=False)

    # Seed der zwei Startvorlagen (Muster wie Migration 6ed174efcf4a für task_columns) -- echte
    # Tabellen, keine SettingOptionGroup, deshalb keine Selbst-Seed-Mechanik.
    now = datetime.utcnow()
    inspection_templates = sa.table(
        'inspection_templates',
        sa.column('id', sa.Integer), sa.column('label', sa.String), sa.column('roof_type', sa.String),
        sa.column('version', sa.Integer), sa.column('description', sa.Text), sa.column('sort_order', sa.Integer),
        sa.column('archived', sa.Boolean), sa.column('created_at', sa.DateTime), sa.column('updated_at', sa.DateTime),
    )
    op.bulk_insert(inspection_templates, [
        {'id': 1, 'label': 'Flachdach Standard', 'roof_type': 'Flachdach', 'version': 1, 'description': None,
         'sort_order': 0, 'archived': False, 'created_at': now, 'updated_at': now},
        {'id': 2, 'label': 'Steildach Ziegel', 'roof_type': 'Steildach', 'version': 1, 'description': None,
         'sort_order': 10, 'archived': False, 'created_at': now, 'updated_at': now},
    ])

    inspection_template_items = sa.table(
        'inspection_template_items',
        sa.column('id', sa.Integer), sa.column('template_id', sa.Integer), sa.column('sort_order', sa.Integer),
        sa.column('group_name', sa.String), sa.column('component_type', sa.String), sa.column('text', sa.String),
        sa.column('item_type', sa.String), sa.column('required', sa.Boolean), sa.column('target_min', sa.Numeric),
        sa.column('target_max', sa.Numeric), sa.column('unit', sa.String), sa.column('photo_required', sa.Boolean),
        sa.column('photo_before_after', sa.Boolean), sa.column('created_at', sa.DateTime), sa.column('updated_at', sa.DateTime),
    )

    def _item(id_, template_id, sort_order, group_name, text, item_type, required=False, component_type=None, unit=None):
        return {
            'id': id_, 'template_id': template_id, 'sort_order': sort_order, 'group_name': group_name,
            'component_type': component_type, 'text': text, 'item_type': item_type, 'required': required,
            'target_min': None, 'target_max': None, 'unit': unit, 'photo_required': False,
            'photo_before_after': False, 'created_at': now, 'updated_at': now,
        }

    flachdach_items = [
        _item(1, 1, 10, 'Allgemein', 'Zugang und Absturzsicherung geprüft', 'ja_nein', required=True),
        _item(2, 1, 20, 'Allgemein', 'Gesamtzustand Dachfläche', 'condition_grade', required=True),
        _item(3, 1, 30, 'Entwässerung', 'Ablauf frei und funktionsfähig', 'ja_nein', required=True, component_type='Gully'),
        _item(4, 1, 40, 'Entwässerung', 'Laubfang vorhanden und intakt', 'ja_nein', component_type='Gully'),
        _item(5, 1, 50, 'Entwässerung', 'frei und funktionsfähig', 'ja_nein', required=True, component_type='Notüberlauf'),
        _item(6, 1, 60, 'Entwässerung', 'gereinigt', 'quantity', component_type='Rinne', unit='lfm'),
        _item(7, 1, 70, 'Entwässerung', 'Durchfluss geprüft', 'ja_nein', component_type='Fallrohr'),
        _item(8, 1, 80, 'Fläche', 'Abdichtung auf Blasen, Risse, Falten', 'condition_grade', required=True),
        _item(9, 1, 90, 'Fläche', 'Abdeckung und Anschluss', 'condition_grade', component_type='Attika'),
        _item(10, 1, 100, 'Fläche', 'Anschlusshöhe und Dichtheit', 'ja_nein', component_type='Wandanschluss'),
        _item(11, 1, 110, 'Fläche', 'Manschette dicht', 'ja_nein', component_type='Durchdringung'),
        _item(12, 1, 120, 'Aufbauten', 'Verglasung und Dichtung', 'condition_grade', component_type='Lichtkuppel'),
        _item(13, 1, 130, 'Aufbauten', 'Funktionsprüfung', 'ja_nein', component_type='RWA'),
        _item(14, 1, 140, 'Aufbauten', 'Sichtprüfung', 'ja_nein', required=True, component_type='Anschlagpunkt'),
        _item(15, 1, 150, 'Abschluss', 'Dichtheitsprüfung', 'leak_test'),
        _item(16, 1, 160, 'Abschluss', 'Bemerkungen', 'free_text'),
    ]
    steildach_items = [
        _item(17, 2, 10, 'Allgemein', 'Zugang und Absturzsicherung geprüft', 'ja_nein', required=True),
        _item(18, 2, 20, 'Allgemein', 'Gesamtzustand Eindeckung', 'condition_grade', required=True),
        _item(19, 2, 30, 'Eindeckung', 'verschobene oder gebrochene Ziegel', 'quantity', unit='Stück'),
        _item(20, 2, 40, 'Eindeckung', 'First und Grat, Verstrichung', 'condition_grade'),
        _item(21, 2, 50, 'Eindeckung', 'Kehlen frei und dicht', 'condition_grade'),
        _item(22, 2, 60, 'Entwässerung', 'gereinigt', 'quantity', component_type='Rinne', unit='lfm'),
        _item(23, 2, 70, 'Entwässerung', 'Durchfluss geprüft', 'ja_nein', component_type='Fallrohr'),
        _item(24, 2, 80, 'Anschlüsse', 'Anschluss und Verwahrung', 'condition_grade', component_type='Schornstein'),
        _item(25, 2, 90, 'Anschlüsse', 'Dichtung und Funktion', 'ja_nein', component_type='Dachfenster'),
        _item(26, 2, 100, 'Anschlüsse', 'Manschette dicht', 'ja_nein', component_type='Durchdringung'),
        _item(27, 2, 110, 'Anschlüsse', 'Sichtprüfung', 'ja_nein', required=True, component_type='Anschlagpunkt'),
        _item(28, 2, 120, 'Abschluss', 'Bemerkungen', 'free_text'),
    ]
    op.bulk_insert(inspection_template_items, flachdach_items + steildach_items)

    with op.batch_alter_table('maintenance_contract_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inspection_template_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_maintenance_contract_items_inspection_template_id', 'inspection_templates', ['inspection_template_id'], ['id'])

    with op.batch_alter_table('service_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('roof_area_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('inspection_template_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('inspection_template_version', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_service_reports_roof_area_id'), ['roof_area_id'], unique=False)
        batch_op.create_foreign_key('fk_service_reports_inspection_template_id', 'inspection_templates', ['inspection_template_id'], ['id'])
        batch_op.create_foreign_key('fk_service_reports_roof_area_id', 'roof_areas', ['roof_area_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_reports', schema=None) as batch_op:
        batch_op.drop_constraint('fk_service_reports_roof_area_id', type_='foreignkey')
        batch_op.drop_constraint('fk_service_reports_inspection_template_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_service_reports_roof_area_id'))
        batch_op.drop_column('inspection_template_version')
        batch_op.drop_column('inspection_template_id')
        batch_op.drop_column('roof_area_id')

    with op.batch_alter_table('maintenance_contract_items', schema=None) as batch_op:
        batch_op.drop_constraint('fk_maintenance_contract_items_inspection_template_id', type_='foreignkey')
        batch_op.drop_column('inspection_template_id')

    with op.batch_alter_table('inspection_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inspection_items_service_report_id'))
        batch_op.drop_index(batch_op.f('ix_inspection_items_client_uuid'))

    op.drop_table('inspection_items')
    with op.batch_alter_table('inspection_template_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inspection_template_items_template_id'))

    op.drop_table('inspection_template_items')
    with op.batch_alter_table('inspection_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inspection_templates_archived'))

    op.drop_table('inspection_templates')
    # ### end Alembic commands ###
