"""checklisten_geraet_repariert

Revision ID: 144a46fc5a97
Revises: 9d6f31f78b88
Create Date: 2026-09-29 11:01:08.566513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '144a46fc5a97'
down_revision = '9d6f31f78b88'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checklist_asset_releases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operational_asset_id', sa.Integer(), nullable=False),
    sa.Column('checklist_id', sa.Integer(), nullable=False),
    sa.Column('released_at', sa.DateTime(), nullable=False),
    sa.Column('released_by_user_id', sa.Integer(), nullable=True),
    sa.Column('released_by_employee_id', sa.Integer(), nullable=True),
    sa.Column('released_by_name', sa.String(length=160), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['checklist_id'], ['checklists.id'], ),
    sa.ForeignKeyConstraint(['operational_asset_id'], ['operational_assets.id'], ),
    sa.ForeignKeyConstraint(['released_by_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['released_by_user_id'], ['app_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('checklist_id', name='uq_checklist_asset_release_checklist')
    )
    with op.batch_alter_table('checklist_asset_releases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checklist_asset_releases_operational_asset_id'), ['operational_asset_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklist_asset_releases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checklist_asset_releases_operational_asset_id'))

    op.drop_table('checklist_asset_releases')
    # ### end Alembic commands ###
