"""wartungsvertrag objekt optional

Revision ID: 14ab5b62113d
Revises: 5c8787a1145b
Create Date: 2026-09-08 19:01:45.630847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14ab5b62113d'
down_revision = '5c8787a1145b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_contracts', schema=None) as batch_op:
        batch_op.alter_column('property_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_contracts', schema=None) as batch_op:
        batch_op.alter_column('property_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
