"""inspection template label snapshot

Revision ID: 14b130f9c315
Revises: 0064c87051aa
Create Date: 2026-09-12 09:15:06.730981

Physischer Namens-Schnappschuss für ServiceReportRoofArea.inspection_template_label_snapshot
(CLAUDE.md "Eingefrorene Bauteil-/Dachflächennamen") -- letzter loser Faden derselben, seit 1.3.12
sonst bereits vollständig eingefrorenen Kette: ein bereits unterschriebener Bericht ist
unveränderlich, zeigte über link.inspection_template.label bisher aber die AKTUELLE statt die
zum Anlagezeitpunkt gültige Vorlagenbezeichnung.

Bestandszeilen (bereits vor dieser Version angelegte ServiceReportRoofArea-Zeilen) haben keinen
historisch korrekten Namen mehr verfügbar -- diese Migration befüllt sie deshalb aus dem HEUTIGEN
Namen der verknüpften InspectionTemplate. Das ist nicht historisch korrekt (der Name könnte
zwischen Anlage und dieser Migration bereits geändert worden sein), aber näher an der Wahrheit als
ein leerer Schnappschuss, der stattdessen bei jedem künftigen Lesezugriff wieder auf den dann
jeweils aktuellen Namen zurückgefallen wäre -- ab dieser Migration ist der Wert eingefroren und
ändert sich nicht mehr mit.
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14b130f9c315'
down_revision = '0064c87051aa'
branch_labels = None
depends_on = None


def _backfill_service_report_roof_area_template_label_snapshots(bind) -> None:
    """Eigene, modulweite Funktion statt in upgrade() verschachtelt (Muster aus 1.2.19/1.3.12,
    siehe CLAUDE.md "Testen" -- Migrationsdatei selbst testen) -- ruft direkt gegen eine gebundene
    Connection auf, unabhängig von batch_alter_table/Operations-Kontext, damit sie sich isoliert
    testen lässt."""
    bind.execute(sa.text(
        "UPDATE service_report_roof_areas SET inspection_template_label_snapshot = "
        "(SELECT label FROM inspection_templates WHERE inspection_templates.id = "
        "service_report_roof_areas.inspection_template_id) "
        "WHERE inspection_template_id IS NOT NULL"
    ))


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_report_roof_areas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inspection_template_label_snapshot', sa.String(length=160), nullable=True))

    # ### end Alembic commands ###

    # Bestandszeilen aus dem HEUTIGEN Namen befüllen -- siehe Modul-Docstring oben für die
    # Begründung, warum das trotz fehlender historischer Korrektheit besser ist als leer.
    bind = op.get_bind()
    _backfill_service_report_roof_area_template_label_snapshots(bind)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_report_roof_areas', schema=None) as batch_op:
        batch_op.drop_column('inspection_template_label_snapshot')

    # ### end Alembic commands ###
