"""Microsoft 365 OAuth2 Graph API als Versandweg

Revision ID: 15b775e5bd3f
Revises: e52a06d5ff38
Create Date: 2026-09-07 09:49:31.929129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15b775e5bd3f'
down_revision = 'e52a06d5ff38'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('smtp_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('send_method', sa.String(length=20), server_default='smtp', nullable=False))
        batch_op.add_column(sa.Column('graph_tenant_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('graph_client_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('graph_client_secret_encrypted', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('graph_sender_mailbox', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('smtp_settings', schema=None) as batch_op:
        batch_op.drop_column('graph_sender_mailbox')
        batch_op.drop_column('graph_client_secret_encrypted')
        batch_op.drop_column('graph_client_id')
        batch_op.drop_column('graph_tenant_id')
        batch_op.drop_column('send_method')

    # ### end Alembic commands ###
