"""two_factor_auth_and_persistent_login_lockout

Revision ID: 1b55170709a6
Revises: 2fffb80e5567
Create Date: 2026-09-13 14:50:30.770594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b55170709a6'
down_revision = '2fffb80e5567'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('failed_login_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bucket', sa.String(length=160), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('failed_login_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_failed_login_attempts_bucket'), ['bucket'], unique=False)
        batch_op.create_index(batch_op.f('ix_failed_login_attempts_occurred_at'), ['occurred_at'], unique=False)

    op.create_table('two_factor_recovery_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.Text(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('two_factor_recovery_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_two_factor_recovery_codes_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('app_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('totp_secret_encrypted', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('totp_confirmed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_users', schema=None) as batch_op:
        batch_op.drop_column('totp_confirmed_at')
        batch_op.drop_column('totp_secret_encrypted')

    with op.batch_alter_table('two_factor_recovery_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_two_factor_recovery_codes_user_id'))

    op.drop_table('two_factor_recovery_codes')
    with op.batch_alter_table('failed_login_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_failed_login_attempts_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_failed_login_attempts_bucket'))

    op.drop_table('failed_login_attempts')
    # ### end Alembic commands ###
