"""property access notes and site contact

Revision ID: 1ccb91b19e8a
Revises: 60d7c8a775f0
Create Date: 2026-09-15 10:20:17.612182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ccb91b19e8a'
down_revision = '60d7c8a775f0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('site_contact_name', sa.String(length=160), nullable=True))
        batch_op.add_column(sa.Column('site_contact_phone', sa.String(length=60), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_column('site_contact_phone')
        batch_op.drop_column('site_contact_name')
        batch_op.drop_column('access_notes')

    # ### end Alembic commands ###
