"""vollmacht_zur_abnahme -- Vollmacht zur Abnahme am Beteiligten, verschobene Gewährleistungsenden (seit 1.8.47)

- project_participants: acceptance_authorized (Häkchen "Vollmacht zur Abnahme", NOT NULL, server_default falsch) und
  acceptance_poa_* (Beleg wie die Empfangsvollmacht, eigene Spalten). Bestand: kein Beteiligter hat sie -- eine
  Empfangsvollmacht genügt für die Abnahme nicht und wird nicht übernommen.
- order_warranty_changes.acceptance_shifts: bei einer Änderung nach der ersten Abnahme die verschobenen Enden (JSON).

downgrade(): bricht ab, solange etwas verloren ginge (ein gesetztes Häkchen, ein Beleg, festgehaltene Verschiebungen).
Belegdateien bleiben ohnehin liegen.

Revision ID: 1dcea6473427
Revises: e15280e3b567
Create Date: 2026-10-04 17:24:28.047525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dcea6473427'
down_revision = 'e15280e3b567'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_warranty_changes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('acceptance_shifts', sa.Text(), nullable=True))

    with op.batch_alter_table('project_participants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('acceptance_authorized', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('acceptance_poa_stored_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('acceptance_poa_original_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('acceptance_poa_content_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('acceptance_poa_size_bytes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('acceptance_poa_sha256', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('acceptance_poa_uploaded_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('acceptance_poa_uploaded_by_name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    bind = op.get_bind()
    counts = {
        "Beteiligte mit Vollmacht zur Abnahme": bind.execute(sa.text(
            "SELECT COUNT(*) FROM project_participants WHERE acceptance_authorized = :ja "
            "OR acceptance_poa_stored_filename IS NOT NULL"), {"ja": True}).scalar(),
        "Festlegungen mit verschobenen Gewährleistungsenden": bind.execute(sa.text(
            "SELECT COUNT(*) FROM order_warranty_changes WHERE acceptance_shifts IS NOT NULL")).scalar(),
    }
    lost = ", ".join(f"{n} {label}" for label, n in counts.items() if n)
    if lost:
        raise RuntimeError(f"Downgrade verweigert: {lost} gingen verloren.")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_participants', schema=None) as batch_op:
        batch_op.drop_column('acceptance_poa_uploaded_by_name')
        batch_op.drop_column('acceptance_poa_uploaded_at')
        batch_op.drop_column('acceptance_poa_sha256')
        batch_op.drop_column('acceptance_poa_size_bytes')
        batch_op.drop_column('acceptance_poa_content_type')
        batch_op.drop_column('acceptance_poa_original_filename')
        batch_op.drop_column('acceptance_poa_stored_filename')
        batch_op.drop_column('acceptance_authorized')

    with op.batch_alter_table('order_warranty_changes', schema=None) as batch_op:
        batch_op.drop_column('acceptance_shifts')

    # ### end Alembic commands ###
