"""E-Mail-Versand fuer Auftraege

Revision ID: 26c9609a8d41
Revises: b9b377efedd0
Create Date: 2026-09-07 12:28:17.045524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26c9609a8d41'
down_revision = 'b9b377efedd0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_sent_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('email_sent_to', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('email_sent_to')
        batch_op.drop_column('email_sent_at')

    # ### end Alembic commands ###
