"""team employee crew leader

Revision ID: 2f5de21f11b8
Revises: fa2105afb89a
Create Date: 2026-09-29 09:03:41.680936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f5de21f11b8'
down_revision = 'fa2105afb89a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_employees', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_crew_leader', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_employees', schema=None) as batch_op:
        batch_op.drop_column('is_crew_leader')

    # ### end Alembic commands ###
