"""properties: is_primary_address flag

Revision ID: 2fffb80e5567
Revises: 9ff6f4131413
Create Date: 2026-09-12 15:41:09.322787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fffb80e5567'
down_revision = '9ff6f4131413'
branch_labels = None
depends_on = None


def _resolve_primary_address_property_ids(bind) -> list[int]:
    """Bestandsabgleich für "Objekte: Hauptadressen kennzeichnen und ausblenden" (siehe
    CLAUDE.md). Markiert wird bewusst nur, wenn ZWEI unabhängige Kriterien übereinstimmen --
    name == "Hauptadresse" (so legt create_customer()/update_customer()/
    _create_customer_from_row() sie an) UND Straße/PLZ/Ort stimmen exakt mit dem Kunden
    überein. Ein Name-Treffer ohne Adressübereinstimmung wird NICHT markiert (könnte ein
    umbenanntes oder nachträglich verändertes Objekt sein) -- lieber eine echte Hauptadresse
    übersehen als eine echte Liegenschaft fälschlich aus der Objektliste verschwinden zu
    lassen. Gegen die echte, migrierte Datenbank geprüft (163 Objekte, Stand 12.09.2026):
    161 von 161 namensgleichen Zeilen erfüllen auch das Adresskriterium -- 0 unsichere Fälle."""
    rows = bind.execute(
        sa.text(
            """
            SELECT p.id
            FROM properties p
            JOIN customers c ON c.id = p.customer_id
            WHERE p.name = 'Hauptadresse'
              AND COALESCE(p.street, '') = COALESCE(c.street, '')
              AND COALESCE(p.postal_code, '') = COALESCE(c.postal_code, '')
              AND COALESCE(p.city, '') = COALESCE(c.city, '')
            """
        )
    ).fetchall()
    return [row[0] for row in rows]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_primary_address', sa.Boolean(), server_default='0', nullable=False))
        batch_op.create_index(batch_op.f('ix_properties_is_primary_address'), ['is_primary_address'], unique=False)

    # ### end Alembic commands ###

    bind = op.get_bind()
    primary_ids = _resolve_primary_address_property_ids(bind)
    if primary_ids:
        bind.execute(
            sa.text("UPDATE properties SET is_primary_address = :is_primary WHERE id IN :ids").bindparams(
                sa.bindparam("ids", expanding=True)
            ),
            {"ids": primary_ids, "is_primary": True},
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_properties_is_primary_address'))
        batch_op.drop_column('is_primary_address')

    # ### end Alembic commands ###
