"""accounts kontenstamm vorkontierung

Revision ID: 329725277349
Revises: fd1cc820d6b7
Create Date: 2026-09-21 18:49:06.255810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '329725277349'
down_revision = 'fd1cc820d6b7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_number', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('default_tax_rate_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_number', name='uq_account_number')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_account_number'), ['account_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_active'), ['active'], unique=False)

    with op.batch_alter_table('incoming_invoice_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_incoming_invoice_items_account_id'), ['account_id'], unique=False)
        # SQLite-Batch-Modus verlangt einen benannten Constraint (baut die Tabelle intern neu
        # auf) -- die autogenerierte Fassung mit `None` scheitert mit "Constraint must have a
        # name", siehe CLAUDE.md "Buchhaltung" -> "Kontenstamm" für den Fund.
        batch_op.create_foreign_key(
            'fk_incoming_invoice_items_account_id_accounts', 'accounts', ['account_id'], ['id']
        )
        batch_op.drop_column('account_code')

    with op.batch_alter_table('incoming_invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_incoming_invoices_account_id'), ['account_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_incoming_invoices_account_id_accounts', 'accounts', ['account_id'], ['id']
        )
        batch_op.drop_column('account_code')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incoming_invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_code', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_constraint('fk_incoming_invoices_account_id_accounts', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_incoming_invoices_account_id'))
        batch_op.drop_column('account_id')

    with op.batch_alter_table('incoming_invoice_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_code', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_constraint('fk_incoming_invoice_items_account_id_accounts', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_incoming_invoice_items_account_id'))
        batch_op.drop_column('account_id')

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_active'))
        batch_op.drop_index(batch_op.f('ix_accounts_account_number'))

    op.drop_table('accounts')
    # ### end Alembic commands ###
