"""calendar event outlook change key

Revision ID: 3e187156fa80
Revises: c137c16e9a5c
Create Date: 2026-09-26 11:53:00.485290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e187156fa80'
down_revision = 'c137c16e9a5c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('outlook_change_key', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.drop_column('outlook_change_key')

    # ### end Alembic commands ###
