"""E-Mail-Versand fuer Rechnungen und Vorlagen-Infrastruktur

Revision ID: 3eb9f52b38ab
Revises: 15b775e5bd3f
Create Date: 2026-09-07 11:38:21.753126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3eb9f52b38ab'
down_revision = '15b775e5bd3f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_email_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=20), nullable=False),
    sa.Column('subject_template', sa.String(length=255), nullable=True),
    sa.Column('body_template', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_type', name='uq_document_email_template_type')
    )
    with op.batch_alter_table('document_email_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_email_templates_document_type'), ['document_type'], unique=False)

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_sent_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('email_sent_to', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_column('email_sent_to')
        batch_op.drop_column('email_sent_at')

    with op.batch_alter_table('document_email_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_email_templates_document_type'))

    op.drop_table('document_email_templates')
    # ### end Alembic commands ###
