"""punkt2_5_6_7_settings_layertype_flags_componenttypes_fax

Revision ID: 4609e3fc8976
Revises: b8adafd0b997
Create Date: 2026-09-09 17:17:24.692413

"""
from datetime import datetime

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4609e3fc8976'
down_revision = 'b8adafd0b997'
branch_labels = None
depends_on = None


# Rückfall für eine frische DB, die die Optionsgruppe roof_component_types nie gesät hat --
# identisch zu den bisherigen Startwerten in app/option_settings.py::DEFAULT_OPTION_GROUPS
# (Gruppe wird mit dieser Migration aus dem Code-Seed entfernt, siehe dort).
DEFAULT_ROOF_COMPONENT_TYPES = [
    (10, "Gully", "Gully"),
    (20, "Notüberlauf", "Notüberlauf"),
    (30, "Rinne", "Rinne"),
    (40, "Fallrohr", "Fallrohr"),
    (50, "Attika", "Attika"),
    (60, "Wandanschluss", "Wandanschluss"),
    (70, "Durchdringung", "Durchdringung"),
    (80, "Lichtkuppel", "Lichtkuppel"),
    (90, "RWA", "RWA"),
    (100, "Schornstein", "Schornstein"),
    (110, "Photovoltaik", "Photovoltaik"),
    (120, "Blitzschutz", "Blitzschutz"),
    (130, "Anschlagpunkt", "Anschlagpunkt"),
    (140, "Dachfenster", "Dachfenster"),
    (150, "Sonstiges", "Sonstiges"),
]


def _resolve_roof_component_type_rows(bind):
    """Liest die TATSÄCHLICHEN setting_options-Zeilen der Gruppe roof_component_types aus der
    DB, statt der Code-Konstante DEFAULT_OPTION_GROUPS zu vertrauen -- seit 1.2.14 kann eine
    Installation über die Einstellungen eigene Bauteilarten angelegt haben, die nur dort stehen.
    Ein reiner Code-Seed würde solche Zeilen verschwinden lassen, obwohl bestehende
    RoofComponent.component_type-Werte sie weiter referenzieren. Fällt die Gruppe komplett aus
    (frische, nie gesäte DB), liefert diese Funktion die 15 Code-Fallback-Werte. Modulweite
    Funktion (nicht in upgrade() verschachtelt), damit ein Test sie direkt gegen eine
    präparierte Verbindung aufrufen kann."""
    group_id = bind.execute(sa.text(
        "SELECT id FROM setting_option_groups WHERE group_key = 'roof_component_types'"
    )).scalar()
    if group_id is None:
        return list(DEFAULT_ROOF_COMPONENT_TYPES)
    rows = bind.execute(sa.text(
        "SELECT sort_order, label, value FROM setting_options "
        "WHERE group_id = :gid AND active = 1 ORDER BY sort_order"
    ), {"gid": group_id}).fetchall()
    if not rows:
        return list(DEFAULT_ROOF_COMPONENT_TYPES)
    return [(row[0], row[1], row[2]) for row in rows]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roof_component_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('is_area', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='100', nullable=False),
    sa.Column('active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    with op.batch_alter_table('roof_component_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roof_component_types_active'), ['active'], unique=False)

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fax', sa.String(length=80), nullable=True))

    with op.batch_alter_table('maintenance_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('use_roof_area_items', sa.Boolean(), server_default='0', nullable=False))

    with op.batch_alter_table('roof_components', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sketch_w', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('sketch_h', sa.Numeric(precision=5, scale=2), nullable=True))

    with op.batch_alter_table('roof_layer_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_execution', sa.Boolean(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('has_notes', sa.Boolean(), server_default='1', nullable=False))

    # ### end Alembic commands ###

    # Datenmigration: has_execution nur dort True, wo bereits eine Ausführungs-Optionsgruppe
    # hinterlegt ist (18 Zeilen ohne option_group -- Konterlattung/Dachlattung/Trennlage sowie
    # die Gründach-Zusatzschichten außer Substrat -- werden explizit False).
    op.execute(
        "UPDATE roof_layer_types SET has_execution = (CASE WHEN option_group IS NOT NULL THEN 1 ELSE 0 END)"
    )
    # has_notes bleibt für alle 25 bestehenden Zeilen True (bereits der server_default) --
    # keine weitere UPDATE nötig, hier nur zur Dokumentation der Entscheidung belassen.

    # Bauteilarten aus den tatsächlichen setting_options-Zeilen übernehmen (siehe Rückfrage 2 /
    # Punkt 6 in CLAUDE.md bzw. der Planung dieser Version).
    bind = op.get_bind()
    now = datetime.utcnow()
    roof_component_types = sa.table(
        'roof_component_types',
        sa.column('key', sa.String), sa.column('label', sa.String), sa.column('is_area', sa.Boolean),
        sa.column('sort_order', sa.Integer), sa.column('active', sa.Boolean),
        sa.column('created_at', sa.DateTime), sa.column('updated_at', sa.DateTime),
    )
    seed_rows = _resolve_roof_component_type_rows(bind)
    op.bulk_insert(roof_component_types, [
        {
            'key': value, 'label': label, 'is_area': value == 'Photovoltaik',
            'sort_order': sort_order, 'active': True, 'created_at': now, 'updated_at': now,
        }
        for sort_order, label, value in seed_rows
    ])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roof_layer_types', schema=None) as batch_op:
        batch_op.drop_column('has_notes')
        batch_op.drop_column('has_execution')

    with op.batch_alter_table('roof_components', schema=None) as batch_op:
        batch_op.drop_column('sketch_h')
        batch_op.drop_column('sketch_w')

    with op.batch_alter_table('maintenance_settings', schema=None) as batch_op:
        batch_op.drop_column('use_roof_area_items')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('fax')

    with op.batch_alter_table('roof_component_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roof_component_types_active'))

    op.drop_table('roof_component_types')
    # ### end Alembic commands ###
