"""sidebar logo dedicated upload

Revision ID: 4ba46163a7e8
Revises: c327ff4ad332
Create Date: 2026-09-14 14:53:00.928581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ba46163a7e8'
down_revision = 'c327ff4ad332'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('general_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sidebar_logo_filename', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('general_settings', schema=None) as batch_op:
        batch_op.drop_column('sidebar_logo_filename')

    # ### end Alembic commands ###
