"""Projekte archivieren

Revision ID: 4d2f2e7b83f3
Revises: c208d96579ce
Create Date: 2026-09-07 13:42:30.891862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d2f2e7b83f3'
down_revision = 'c208d96579ce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived', sa.Boolean(), server_default='0', nullable=False))
        batch_op.create_index(batch_op.f('ix_projects_archived'), ['archived'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_archived'))
        batch_op.drop_column('archived')

    # ### end Alembic commands ###
