"""Randabstaende je Seitentyp

Revision ID: 4d6a0e28804a
Revises: ef7b95affc19
Create Date: 2026-09-05 12:11:37.903665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d6a0e28804a'
down_revision = 'ef7b95affc19'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_page_margins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=20), nullable=False),
    sa.Column('page_type', sa.String(length=20), nullable=False),
    sa.Column('top_mm', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('bottom_mm', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('left_mm', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('right_mm', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_type', 'page_type', name='uq_document_page_margins')
    )
    with op.batch_alter_table('document_page_margins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_page_margins_document_type'), ['document_type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_page_margins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_page_margins_document_type'))

    op.drop_table('document_page_margins')
    # ### end Alembic commands ###
