"""finding and service_report_roof_area name snapshots

Revision ID: 5149d369dbb6
Revises: 257fb2967c93
Create Date: 2026-09-11 14:32:36.403634

Physischer Namens-Schnappschuss für Finding.roof_component_name_snapshot/
ServiceReportRoofArea.roof_area_name_snapshot (CLAUDE.md "Eingefrorene Bauteil-/
Dachflächennamen") -- dieselbe Begründung wie bei InspectionItem.text seit 1.2.16: ein bereits
unterschriebener Bericht ist unveränderlich, zeigte über finding.roof_component.name/
link.roof_area.name aber bisher den AKTUELLEN statt den zum Signierzeitpunkt gültigen Namen.

Bestandszeilen (bereits vor dieser Version angelegte Findings/ServiceReportRoofArea-Zeilen)
haben keinen historisch korrekten Namen mehr verfügbar -- diese Migration befüllt sie deshalb
aus dem HEUTIGEN Namen des verknüpften RoofComponent/RoofArea-Datensatzes. Das ist nicht
historisch korrekt (der Name könnte zwischen Anlage und dieser Migration bereits geändert worden
sein), aber näher an der Wahrheit als ein leerer Schnappschuss, der stattdessen bei jedem
künftigen Lesezugriff wieder auf den dann jeweils aktuellen Namen zurückgefallen wäre -- ab
dieser Migration ist der Wert eingefroren und ändert sich nicht mehr mit.
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5149d369dbb6'
down_revision = '257fb2967c93'
branch_labels = None
depends_on = None


def _backfill_finding_roof_component_snapshots(bind) -> None:
    """Eigene, modulweite Funktion statt in upgrade() verschachtelt (Muster aus 1.2.19, siehe
    CLAUDE.md "Testen" -- Migrationsdatei selbst testen) -- ruft direkt gegen eine gebundene
    Connection auf, unabhängig von batch_alter_table/Operations-Kontext, damit sie sich isoliert
    testen lässt."""
    bind.execute(sa.text(
        "UPDATE findings SET roof_component_name_snapshot = "
        "(SELECT name FROM roof_components WHERE roof_components.id = findings.roof_component_id) "
        "WHERE roof_component_id IS NOT NULL"
    ))


def _backfill_service_report_roof_area_snapshots(bind) -> None:
    bind.execute(sa.text(
        "UPDATE service_report_roof_areas SET roof_area_name_snapshot = "
        "(SELECT name FROM roof_areas WHERE roof_areas.id = service_report_roof_areas.roof_area_id)"
    ))


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('roof_component_name_snapshot', sa.String(length=255), nullable=True))

    with op.batch_alter_table('service_report_roof_areas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('roof_area_name_snapshot', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###

    # Bestandszeilen aus dem HEUTIGEN Namen befüllen -- siehe Modul-Docstring oben für die
    # Begründung, warum das trotz fehlender historischer Korrektheit besser ist als leer.
    bind = op.get_bind()
    _backfill_finding_roof_component_snapshots(bind)
    _backfill_service_report_roof_area_snapshots(bind)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_report_roof_areas', schema=None) as batch_op:
        batch_op.drop_column('roof_area_name_snapshot')

    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.drop_column('roof_component_name_snapshot')

    # ### end Alembic commands ###
