"""Mahnwesen-Automatisierung: automatische Entwuerfe

Revision ID: 53778598ef1d
Revises: 4d6a0e28804a
Create Date: 2026-09-07 07:01:50.781427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53778598ef1d'
down_revision = '4d6a0e28804a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('general_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reminders_auto_create_drafts', sa.Boolean(), server_default='1', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('general_settings', schema=None) as batch_op:
        batch_op.drop_column('reminders_auto_create_drafts')

    # ### end Alembic commands ###
