"""productive hours settings and recurring cost overhead classification

Revision ID: 57062a31dba7
Revises: fc79aa5629d0
Create Date: 2026-09-18 19:02:52.673086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57062a31dba7'
down_revision = 'fc79aa5629d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productive_hours_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weekly_hours', sa.Numeric(precision=9, scale=4), nullable=False),
    sa.Column('daily_hours', sa.Numeric(precision=9, scale=4), nullable=False),
    sa.Column('vacation_days', sa.Numeric(precision=9, scale=4), nullable=False),
    sa.Column('public_holidays', sa.Numeric(precision=9, scale=4), nullable=False),
    sa.Column('average_sick_days', sa.Numeric(precision=9, scale=4), nullable=False),
    sa.Column('weather_loss_days', sa.Numeric(precision=9, scale=4), nullable=False),
    sa.Column('unproductive_time_pct', sa.Numeric(precision=9, scale=4), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recurring_costs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('overhead_classification', sa.String(length=20), server_default='keine', nullable=False))
        batch_op.create_index(batch_op.f('ix_recurring_costs_overhead_classification'), ['overhead_classification'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recurring_costs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recurring_costs_overhead_classification'))
        batch_op.drop_column('overhead_classification')

    op.drop_table('productive_hours_settings')
    # ### end Alembic commands ###
