"""PDF-Layoutdesigner: DocumentLayoutBlock und Firmenlogo

Revision ID: 58e4e0719407
Revises: 6285c0bb4e0d
Create Date: 2026-09-04 18:09:19.455371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58e4e0719407'
down_revision = '6285c0bb4e0d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_layout_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=20), nullable=False),
    sa.Column('block_type', sa.String(length=30), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('x_mm', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('y_mm', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('width_mm', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('height_mm', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('font_size', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('font_weight', sa.String(length=10), nullable=False),
    sa.Column('text_align', sa.String(length=10), nullable=False),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_layout_blocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_layout_blocks_document_type'), ['document_type'], unique=False)

    with op.batch_alter_table('general_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_filename', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('general_settings', schema=None) as batch_op:
        batch_op.drop_column('logo_filename')

    with op.batch_alter_table('document_layout_blocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_layout_blocks_document_type'))

    op.drop_table('document_layout_blocks')
    # ### end Alembic commands ###
