"""operational assets betriebsmittel

Revision ID: 5917bb099776
Revises: da9d9425e257
Create Date: 2026-09-17 20:06:35.900249

Backfill (Regel 1 sinngemäß -- die Tabelle selbst ist neu, aber ihr Inhalt darf existierende
OperationalResource-Zeilen nicht unsichtbar machen, sobald die Stammdaten-Oberfläche auf
Assets umgestellt wird): für jede bereits bestehende OperationalResource wird eine verknüpfte
OperationalAsset-Zeile angelegt (resource_id gesetzt, eigene Identitätsfelder bleiben NULL,
da sie bei verknüpften Assets ohnehin live von der Ressource gelesen werden, siehe
app/operational_assets.py::asset_to_dict()). _backfill_assets_for_existing_resources() ist
als eigenständige, direkt gegen eine Connection testbare Funktion ausgelagert (Muster aus
1.2.19/1.3.12/1.3.22, siehe CLAUDE.md "Testen")."""
from datetime import datetime

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5917bb099776'
down_revision = 'da9d9425e257'
branch_labels = None
depends_on = None


def _backfill_assets_for_existing_resources(bind) -> int:
    resource_ids = [row[0] for row in bind.execute(sa.text("SELECT id FROM operational_resources")).fetchall()]
    if not resource_ids:
        return 0
    now = datetime.utcnow()
    assets_table = sa.table(
        "operational_assets",
        sa.column("resource_id"), sa.column("active"), sa.column("created_at"), sa.column("updated_at"),
    )
    bind.execute(
        assets_table.insert(),
        [{"resource_id": rid, "active": True, "created_at": now, "updated_at": now} for rid in resource_ids],
    )
    return len(resource_ids)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operational_asset_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reminder_lead_days', sa.Integer(), server_default='30', nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operational_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('asset_number', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('asset_type', sa.String(length=50), nullable=True),
    sa.Column('manufacturer', sa.String(length=120), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('identifier', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('acquisition_date', sa.Date(), nullable=True),
    sa.Column('acquisition_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('recurring_cost_per_month', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cost_notes', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['operational_resources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_id', name='uq_operational_asset_resource')
    )
    with op.batch_alter_table('operational_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operational_assets_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_operational_assets_asset_number'), ['asset_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_operational_assets_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_operational_assets_resource_id'), ['resource_id'], unique=False)

    op.create_table('operational_asset_inspections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('inspection_type', sa.String(length=80), nullable=False),
    sa.Column('interval_months', sa.Integer(), nullable=True),
    sa.Column('last_inspection_date', sa.Date(), nullable=True),
    sa.Column('next_due_date', sa.Date(), nullable=True),
    sa.Column('inspector', sa.String(length=160), nullable=True),
    sa.Column('document_filename', sa.String(length=255), nullable=True),
    sa.Column('document_original_name', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['operational_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('operational_asset_inspections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operational_asset_inspections_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_operational_asset_inspections_inspection_type'), ['inspection_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_operational_asset_inspections_next_due_date'), ['next_due_date'], unique=False)

    # ### end Alembic commands ###

    _backfill_assets_for_existing_resources(op.get_bind())


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operational_asset_inspections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operational_asset_inspections_next_due_date'))
        batch_op.drop_index(batch_op.f('ix_operational_asset_inspections_inspection_type'))
        batch_op.drop_index(batch_op.f('ix_operational_asset_inspections_asset_id'))

    op.drop_table('operational_asset_inspections')
    with op.batch_alter_table('operational_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operational_assets_resource_id'))
        batch_op.drop_index(batch_op.f('ix_operational_assets_name'))
        batch_op.drop_index(batch_op.f('ix_operational_assets_asset_number'))
        batch_op.drop_index(batch_op.f('ix_operational_assets_active'))

    op.drop_table('operational_assets')
    op.drop_table('operational_asset_settings')
    # ### end Alembic commands ###
