"""add maintenance settings table

Revision ID: 5c8787a1145b
Revises: 2ba59ab6f30a
Create Date: 2026-09-08 18:11:21.808924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c8787a1145b'
down_revision = '2ba59ab6f30a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reminder_lead_days', sa.Integer(), server_default='30', nullable=False),
    sa.Column('default_responsible_employee_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['default_responsible_employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('maintenance_settings')
    # ### end Alembic commands ###
