"""checklisten_unterzeichner -- Unterzeichner je Unterschriftsfeld und im Siegel (seit 1.8.57, Stufe 2c-2c, Punkt 3)

- checklist_template_fields.signer_mode: NOT NULL, server_default "frei" (Regel 1) -- alle vorhandenen Felder bleiben, wie
  sie waren (Name eintippen). Auch an veröffentlichten Fassungen: "frei" beschreibt genau ihr bisheriges Verhalten.
- checklist_attachments: signer_kind, signer_user_id (ohne Fremdschlüssel, Befund "Benutzer löschen" 1.8.13),
  signer_participant_id (Fremdschlüssel auf project_participants, Index), signer_role, signer_poa_stored_filename,
  signer_poa_content_type, signer_poa_sha256, seal_format -- alle nullable. Vorhandene Unterschriften bleiben leer: ihr
  Siegel (Format 2 mit Kopie bzw. 1.8.13 ohne) wird weiter nach seinem eigenen Format geprüft und bleibt gültig.

downgrade(): verweigert, sobald eine Unterschrift im Siegelformat 3 existiert oder ein Feld einen anderen Unterzeichner als
"frei" hat -- 1.8.56 kennt den Unterzeichner im Siegel nicht und würde jede solche Unterschrift als "weicht ab" melden, und die
Kopien der Vollmachten verlören ihren Verweis. Ohne solche Zeilen entfernt er die Spalten.

Revision ID: 5e562a4a172b
Revises: 90a5ff1e1714
Create Date: 2026-10-05 15:52:28.809013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e562a4a172b'
down_revision = '90a5ff1e1714'
branch_labels = None
depends_on = None

FK_NAME = "fk_checklist_attachments_signer_participant_id"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklist_attachments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signer_kind', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('signer_user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('signer_participant_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('signer_role', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('signer_poa_stored_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('signer_poa_content_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('signer_poa_sha256', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('seal_format', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_checklist_attachments_signer_participant_id'), ['signer_participant_id'], unique=False)
        batch_op.create_foreign_key(FK_NAME, 'project_participants', ['signer_participant_id'], ['id'])

    with op.batch_alter_table('checklist_template_fields', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signer_mode', sa.String(length=20), server_default='frei', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    bind = op.get_bind()
    counts = {
        "Unterschriften mit Unterzeichner im Siegel": bind.execute(sa.text(
            "SELECT COUNT(*) FROM checklist_attachments WHERE seal_format IS NOT NULL OR signer_kind IS NOT NULL")).scalar(),
        "Unterschriftsfelder mit festem Unterzeichner": bind.execute(sa.text(
            "SELECT COUNT(*) FROM checklist_template_fields WHERE signer_mode <> 'frei'")).scalar(),
    }
    lost = ", ".join(f"{n} {label}" for label, n in counts.items() if n)
    if lost:
        raise RuntimeError(f"Downgrade verweigert: {lost} gingen verloren bzw. passten nicht mehr zu ihrem Siegel.")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklist_template_fields', schema=None) as batch_op:
        batch_op.drop_column('signer_mode')

    with op.batch_alter_table('checklist_attachments', schema=None) as batch_op:
        batch_op.drop_constraint(FK_NAME, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_checklist_attachments_signer_participant_id'))
        batch_op.drop_column('seal_format')
        batch_op.drop_column('signer_poa_sha256')
        batch_op.drop_column('signer_poa_content_type')
        batch_op.drop_column('signer_poa_stored_filename')
        batch_op.drop_column('signer_role')
        batch_op.drop_column('signer_participant_id')
        batch_op.drop_column('signer_user_id')
        batch_op.drop_column('signer_kind')

    # ### end Alembic commands ###
