"""add accent_color to general_settings

Revision ID: 609b69008de8
Revises: 4d2f2e7b83f3
Create Date: 2026-09-07 17:05:57.035062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '609b69008de8'
down_revision = '4d2f2e7b83f3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('general_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accent_color', sa.String(length=20), server_default='#0d9488', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('general_settings', schema=None) as batch_op:
        batch_op.drop_column('accent_color')

    # ### end Alembic commands ###
