"""maengel_aus_der_abnahme -- Mängel aus der Abnahme mit Verlauf und Dateien (seit 1.8.49, Stufe 2c-2a)

- defects: Mangel an einer Abnahme (Quelle "abnahme"), Beschreibung, Dachfläche (Name als Schnappschuss), Ortsangabe,
  Beseitigungsfrist, Aufgabe (task_id ohne Fremdschlüssel), Prüfsumme mit Fassung, Verwerfen mit Siegel.
- defect_events: Haltung, Status, Freigabe, nachgereichte Fotos -- unveränderlich, in einer Kette versiegelt.
- defect_files: Fotos, Belege, Vollmacht zur Abnahme (Kopie); die Dateien selbst liegen in der Ablage der Abnahme.
Neue Tabellen, kein Bestand berührt.

downgrade(): bricht ab, solange ein Mangel besteht (Verlauf und Dateien gingen verloren). Dateien bleiben ohnehin liegen.

Revision ID: 60f193510ae2
Revises: 9c5a97bc71ef
Create Date: 2026-10-05 08:15:40.975676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60f193510ae2'
down_revision = '9c5a97bc71ef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('defects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('acceptance_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('roof_area_id', sa.Integer(), nullable=True),
    sa.Column('roof_area_name', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('remedy_due_on', sa.Date(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('checksum_format', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_by_name', sa.String(length=160), nullable=False),
    sa.Column('discarded_at', sa.DateTime(), nullable=True),
    sa.Column('discarded_by_user_id', sa.Integer(), nullable=True),
    sa.Column('discarded_by_name', sa.String(length=160), nullable=True),
    sa.Column('discard_reason', sa.Text(), nullable=True),
    sa.Column('discard_sha256', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['acceptance_id'], ['order_acceptances.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['roof_area_id'], ['roof_areas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('defects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_defects_acceptance_id'), ['acceptance_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_defects_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_defects_property_id'), ['property_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_defects_roof_area_id'), ['roof_area_id'], unique=False)

    op.create_table('defect_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('defect_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('value', sa.String(length=30), nullable=True),
    sa.Column('previous_value', sa.String(length=30), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('declared_by', sa.String(length=20), nullable=True),
    sa.Column('participant_id', sa.Integer(), nullable=True),
    sa.Column('declared_by_name', sa.String(length=255), nullable=True),
    sa.Column('declared_by_role', sa.String(length=120), nullable=True),
    sa.Column('poa_on_record', sa.Boolean(), nullable=True),
    sa.Column('previous_event_sha256', sa.String(length=64), nullable=True),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('checksum_format', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_by_name', sa.String(length=160), nullable=False),
    sa.ForeignKeyConstraint(['defect_id'], ['defects.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['project_participants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('defect_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_defect_events_defect_id'), ['defect_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_defect_events_participant_id'), ['participant_id'], unique=False)

    op.create_table('defect_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('defect_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['defect_id'], ['defects.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['defect_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('defect_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_defect_files_defect_id'), ['defect_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_defect_files_event_id'), ['event_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    count = op.get_bind().execute(sa.text("SELECT COUNT(*) FROM defects")).scalar()
    if count:
        raise RuntimeError(f"Downgrade verweigert: {count} Mängel samt Verlauf gingen verloren.")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('defect_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_defect_files_event_id'))
        batch_op.drop_index(batch_op.f('ix_defect_files_defect_id'))

    op.drop_table('defect_files')
    with op.batch_alter_table('defect_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_defect_events_participant_id'))
        batch_op.drop_index(batch_op.f('ix_defect_events_defect_id'))

    op.drop_table('defect_events')
    with op.batch_alter_table('defects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_defects_roof_area_id'))
        batch_op.drop_index(batch_op.f('ix_defects_property_id'))
        batch_op.drop_index(batch_op.f('ix_defects_order_id'))
        batch_op.drop_index(batch_op.f('ix_defects_acceptance_id'))

    op.drop_table('defects')
    # ### end Alembic commands ###
