"""wartungsfenster und positionen

Revision ID: 623c88dc1bae
Revises: bfe5e08483b0
Create Date: 2026-09-09 11:01:29.728808

"""
from datetime import datetime

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '623c88dc1bae'
down_revision = 'bfe5e08483b0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_windows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('month_from', sa.Integer(), nullable=False),
    sa.Column('month_to', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='100', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    # Seed der beiden Standard-Fenster (Muster wie Migration 6ed174efcf4a für task_columns) --
    # eine echte Tabelle, kein SettingOptionGroup, deshalb keine Selbst-Seed-Mechanik.
    now = datetime.utcnow()
    maintenance_windows = sa.table(
        'maintenance_windows',
        sa.column('id', sa.Integer), sa.column('label', sa.String),
        sa.column('month_from', sa.Integer), sa.column('month_to', sa.Integer),
        sa.column('sort_order', sa.Integer),
        sa.column('created_at', sa.DateTime), sa.column('updated_at', sa.DateTime),
    )
    op.bulk_insert(maintenance_windows, [
        {'id': 1, 'label': 'Frühjahr', 'month_from': 3, 'month_to': 5, 'sort_order': 0, 'created_at': now, 'updated_at': now},
        {'id': 2, 'label': 'Herbst', 'month_from': 10, 'month_to': 11, 'sort_order': 10, 'created_at': now, 'updated_at': now},
    ])

    op.create_table('maintenance_contract_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('roof_area_id', sa.Integer(), nullable=False),
    sa.Column('maintenance_window_id', sa.Integer(), nullable=False),
    sa.Column('template_project_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('next_due_date', sa.Date(), nullable=False),
    sa.Column('last_reminder_due_date', sa.Date(), nullable=True),
    sa.Column('archived', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['maintenance_contracts.id'], ),
    sa.ForeignKeyConstraint(['maintenance_window_id'], ['maintenance_windows.id'], ),
    sa.ForeignKeyConstraint(['roof_area_id'], ['roof_areas.id'], ),
    sa.ForeignKeyConstraint(['template_project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('maintenance_contract_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maintenance_contract_items_archived'), ['archived'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_contract_items_contract_id'), ['contract_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_contract_items_maintenance_window_id'), ['maintenance_window_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_contract_items_roof_area_id'), ['roof_area_id'], unique=False)

    with op.batch_alter_table('project_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_maintenance_contract_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('source_maintenance_contract_item_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_project_profiles_source_maintenance_contract_id'), ['source_maintenance_contract_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_profiles_source_maintenance_contract_item_id'), ['source_maintenance_contract_item_id'], unique=False)
        batch_op.create_foreign_key('fk_project_profiles_source_maintenance_contract_id', 'maintenance_contracts', ['source_maintenance_contract_id'], ['id'])
        batch_op.create_foreign_key('fk_project_profiles_source_maintenance_contract_item_id', 'maintenance_contract_items', ['source_maintenance_contract_item_id'], ['id'])

    with op.batch_alter_table('service_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('maintenance_contract_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('maintenance_contract_item_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_service_reports_maintenance_contract_id'), ['maintenance_contract_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_reports_maintenance_contract_item_id'), ['maintenance_contract_item_id'], unique=False)
        batch_op.create_foreign_key('fk_service_reports_maintenance_contract_item_id', 'maintenance_contract_items', ['maintenance_contract_item_id'], ['id'])
        batch_op.create_foreign_key('fk_service_reports_maintenance_contract_id', 'maintenance_contracts', ['maintenance_contract_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_reports', schema=None) as batch_op:
        batch_op.drop_constraint('fk_service_reports_maintenance_contract_item_id', type_='foreignkey')
        batch_op.drop_constraint('fk_service_reports_maintenance_contract_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_service_reports_maintenance_contract_item_id'))
        batch_op.drop_index(batch_op.f('ix_service_reports_maintenance_contract_id'))
        batch_op.drop_column('maintenance_contract_item_id')
        batch_op.drop_column('maintenance_contract_id')

    with op.batch_alter_table('project_profiles', schema=None) as batch_op:
        batch_op.drop_constraint('fk_project_profiles_source_maintenance_contract_id', type_='foreignkey')
        batch_op.drop_constraint('fk_project_profiles_source_maintenance_contract_item_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_project_profiles_source_maintenance_contract_item_id'))
        batch_op.drop_index(batch_op.f('ix_project_profiles_source_maintenance_contract_id'))
        batch_op.drop_column('source_maintenance_contract_item_id')
        batch_op.drop_column('source_maintenance_contract_id')

    with op.batch_alter_table('maintenance_contract_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maintenance_contract_items_roof_area_id'))
        batch_op.drop_index(batch_op.f('ix_maintenance_contract_items_maintenance_window_id'))
        batch_op.drop_index(batch_op.f('ix_maintenance_contract_items_contract_id'))
        batch_op.drop_index(batch_op.f('ix_maintenance_contract_items_archived'))

    op.drop_table('maintenance_contract_items')
    op.drop_table('maintenance_windows')
    # ### end Alembic commands ###
