"""Dokumentenmanagement: customer_documents und subfolder

Revision ID: 6285c0bb4e0d
Revises: 0946c1a4c4be
Create Date: 2026-09-04 17:26:40.991584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6285c0bb4e0d'
down_revision = '0946c1a4c4be'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('subfolder', sa.String(length=150), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=150), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('document_date', sa.Date(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_filename')
    )
    with op.batch_alter_table('customer_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_documents_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_documents_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_documents_subfolder'), ['subfolder'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_documents_uploaded_at'), ['uploaded_at'], unique=False)

    with op.batch_alter_table('project_documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subfolder', sa.String(length=150), nullable=True))
        batch_op.create_index(batch_op.f('ix_project_documents_subfolder'), ['subfolder'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_documents_subfolder'))
        batch_op.drop_column('subfolder')

    with op.batch_alter_table('customer_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_documents_uploaded_at'))
        batch_op.drop_index(batch_op.f('ix_customer_documents_subfolder'))
        batch_op.drop_index(batch_op.f('ix_customer_documents_customer_id'))
        batch_op.drop_index(batch_op.f('ix_customer_documents_category'))

    op.drop_table('customer_documents')
    # ### end Alembic commands ###
