"""outlook calendar sync stufe 2

Revision ID: 6573d677bc1d
Revises: 7974647223ea
Create Date: 2026-09-26 08:48:39.304460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6573d677bc1d'
down_revision = '7974647223ea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outlook_sync_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('outlook_calendar_sync_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_user_id', sa.Integer(), nullable=False),
    sa.Column('delta_link', sa.Text(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('last_error_type', sa.String(length=120), nullable=True),
    sa.Column('last_error_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['app_user_id'], ['app_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('app_user_id', name='uq_outlook_sync_state_app_user_id')
    )
    with op.batch_alter_table('outlook_calendar_sync_state', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outlook_calendar_sync_state_app_user_id'), ['app_user_id'], unique=False)

    with op.batch_alter_table('app_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('outlook_mailbox', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_users', schema=None) as batch_op:
        batch_op.drop_column('outlook_mailbox')

    with op.batch_alter_table('outlook_calendar_sync_state', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outlook_calendar_sync_state_app_user_id'))

    op.drop_table('outlook_calendar_sync_state')
    op.drop_table('outlook_sync_settings')
    # ### end Alembic commands ###
