"""maengel_meldung_monteur -- Kennung der Meldung "beseitigt" aus der Monteursansicht (seit 1.8.52, Stufe 2c-2b)

- defect_events.client_uuid: nullable, UNIQUE (uq_defect_event_client_uuid). Gesetzt nur bei der Meldung eines Monteurs
  (app/defects.py::report_remedied()); dieselbe Kennung noch einmal liefert die gespeicherte Meldung (Stufe 3, offline).
  Vorhandene Einträge bleiben leer -- sie kommen aus dem Büro.

downgrade(): entfernt Spalte und Schlüssel ohne Rückfrage. Verloren gehen nur die Kennungen; die Meldungen selbst bleiben
gültige Einträge im Verlauf (die Kennung steht nicht im gebundenen Inhalt, 1.8.51 rechnet sie unverändert nach).

Revision ID: 6c7610e54ce3
Revises: 60f193510ae2
Create Date: 2026-10-05 11:19:38.252295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c7610e54ce3'
down_revision = '60f193510ae2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('defect_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_uuid', sa.String(length=36), nullable=True))
        batch_op.create_unique_constraint('uq_defect_event_client_uuid', ['client_uuid'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('defect_events', schema=None) as batch_op:
        batch_op.drop_constraint('uq_defect_event_client_uuid', type_='unique')
        batch_op.drop_column('client_uuid')

    # ### end Alembic commands ###
