"""add service reports table

Revision ID: 6d2ca9ae3761
Revises: f866cb9b23e7
Create Date: 2026-09-08 16:53:31.494926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d2ca9ae3761'
down_revision = 'f866cb9b23e7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by_employee_id', sa.Integer(), nullable=True),
    sa.Column('performed_at', sa.Date(), nullable=False),
    sa.Column('signature_path', sa.String(length=255), nullable=True),
    sa.Column('signature_name', sa.String(length=160), nullable=True),
    sa.Column('signed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='entwurf', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_reports_order_id'), ['order_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_reports_order_id'))

    op.drop_table('service_reports')
    # ### end Alembic commands ###
