"""add task columns checklist items and task settings

Revision ID: 6ed174efcf4a
Revises: 9609f7401158
Create Date: 2026-09-08 14:28:39.678824

"""
from datetime import datetime

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ed174efcf4a'
down_revision = '9609f7401158'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_columns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_done', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', name='uq_task_column_key')
    )
    op.create_table('task_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notify_on_assignment', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_checklist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('done', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_checklist_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_checklist_items_task_id'), ['task_id'], unique=False)

    # ### end Alembic commands ###

    # Daten-Seed: die drei zuvor fest kodierten Status offen/in_arbeit/erledigt werden als
    # Start-Spalten angelegt, damit bestehende Aufgaben (Task.status) nach dem Upgrade
    # nahtlos weiterlaufen -- ohne diesen Seed würde task_to_dict() für jede bestehende
    # Aufgabe keine passende Spalte finden.
    now = datetime.utcnow()
    task_columns = sa.table(
        'task_columns',
        sa.column('id', sa.Integer), sa.column('key', sa.String), sa.column('label', sa.String),
        sa.column('sort_order', sa.Integer), sa.column('is_done', sa.Boolean), sa.column('created_at', sa.DateTime),
    )
    op.bulk_insert(task_columns, [
        {'id': 1, 'key': 'offen', 'label': 'Offen', 'sort_order': 0, 'is_done': False, 'created_at': now},
        {'id': 2, 'key': 'in_arbeit', 'label': 'In Arbeit', 'sort_order': 10, 'is_done': False, 'created_at': now},
        {'id': 3, 'key': 'erledigt', 'label': 'Erledigt', 'sort_order': 20, 'is_done': True, 'created_at': now},
    ])
    task_settings = sa.table(
        'task_settings',
        sa.column('id', sa.Integer), sa.column('notify_on_assignment', sa.Boolean), sa.column('updated_at', sa.DateTime),
    )
    op.bulk_insert(task_settings, [{'id': 1, 'notify_on_assignment': True, 'updated_at': now}])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_checklist_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_checklist_items_task_id'))

    op.drop_table('task_checklist_items')
    op.drop_table('task_settings')
    op.drop_table('task_columns')
    # ### end Alembic commands ###
