"""calendar events kalender modul

Revision ID: 7974647223ea
Revises: d87d5bc04b69
Create Date: 2026-09-24 09:43:06.192040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7974647223ea'
down_revision = 'd87d5bc04b69'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('end_at', sa.DateTime(), nullable=False),
    sa.Column('all_day', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('quote_id', sa.Integer(), nullable=True),
    sa.Column('is_private', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('outlook_event_id', sa.String(length=255), nullable=True),
    sa.Column('external_source', sa.String(length=20), server_default='erp', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['app_users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calendar_events_end_at'), ['end_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_events_outlook_event_id'), ['outlook_event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_events_owner_user_id'), ['owner_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_events_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_events_quote_id'), ['quote_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_events_start_at'), ['start_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calendar_events_start_at'))
        batch_op.drop_index(batch_op.f('ix_calendar_events_quote_id'))
        batch_op.drop_index(batch_op.f('ix_calendar_events_project_id'))
        batch_op.drop_index(batch_op.f('ix_calendar_events_owner_user_id'))
        batch_op.drop_index(batch_op.f('ix_calendar_events_outlook_event_id'))
        batch_op.drop_index(batch_op.f('ix_calendar_events_end_at'))

    op.drop_table('calendar_events')
    # ### end Alembic commands ###
