"""maengel_aus_protokoll -- Mängel aus dem Feld "Mängel" eines Abnahmeprotokolls (seit 1.8.60, Stufe 2c-2d, Punkt 1)

- defects.checklist_id: nullable, Fremdschlüssel auf checklists (benannt, damit er sich auch unter SQLite zurücknehmen lässt),
  Index. Gesetzt nur bei source "protokoll" (app/defects.py::create_protocol_defect()); vorhandene Mängel (source "abnahme")
  bleiben leer.

downgrade(): verweigert, solange ein Mangel aus einem Protokoll existiert -- er verlöre seine Herkunft, und sein gebundener
Inhalt (mit checklist_id) passte nicht mehr.

Revision ID: 82e4382b0c9f
Revises: cd0d94c87f0c
Create Date: 2026-10-05

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82e4382b0c9f'
down_revision = 'cd0d94c87f0c'
branch_labels = None
depends_on = None

FK_NAME = "fk_defects_checklist_id"


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('defects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checklist_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_defects_checklist_id'), ['checklist_id'], unique=False)
        batch_op.create_foreign_key(FK_NAME, 'checklists', ['checklist_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    count = op.get_bind().execute(sa.text("SELECT COUNT(*) FROM defects WHERE checklist_id IS NOT NULL")).scalar()
    if count:
        raise RuntimeError(f"Downgrade verweigert: {count} Mängel stammen aus einem Abnahmeprotokoll -- sie verlören ihre "
                           "Herkunft, und ihr gebundener Inhalt passte nicht mehr.")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('defects', schema=None) as batch_op:
        batch_op.drop_constraint(FK_NAME, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_defects_checklist_id'))
        batch_op.drop_column('checklist_id')

    # ### end Alembic commands ###
