"""archivieren fuer wartungsvertraege und aufgaben

Revision ID: 8adb7e406857
Revises: 14ab5b62113d
Create Date: 2026-09-08 19:17:01.425150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8adb7e406857'
down_revision = '14ab5b62113d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_contracts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived', sa.Boolean(), server_default='0', nullable=False))
        batch_op.create_index(batch_op.f('ix_maintenance_contracts_archived'), ['archived'], unique=False)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived', sa.Boolean(), server_default='0', nullable=False))
        batch_op.create_index(batch_op.f('ix_tasks_archived'), ['archived'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_archived'))
        batch_op.drop_column('archived')

    with op.batch_alter_table('maintenance_contracts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maintenance_contracts_archived'))
        batch_op.drop_column('archived')

    # ### end Alembic commands ###
