"""findings and service report photos

Revision ID: 8c6c6860cc71
Revises: 09b654357a58
Create Date: 2026-09-09 13:47:10.440811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c6c6860cc71'
down_revision = '09b654357a58'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_report_id', sa.Integer(), nullable=False),
    sa.Column('inspection_item_id', sa.Integer(), nullable=True),
    sa.Column('roof_component_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('follow_up_order_id', sa.Integer(), nullable=True),
    sa.Column('follow_up_project_id', sa.Integer(), nullable=True),
    sa.Column('follow_up_task_id', sa.Integer(), nullable=True),
    sa.Column('resubmission_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='offen', nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('closed_by_employee_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_employee_id', sa.Integer(), nullable=True),
    sa.Column('client_uuid', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['closed_by_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['created_by_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['follow_up_order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['follow_up_project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['follow_up_task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['inspection_item_id'], ['inspection_items.id'], ),
    sa.ForeignKeyConstraint(['roof_component_id'], ['roof_components.id'], ),
    sa.ForeignKeyConstraint(['service_report_id'], ['service_reports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_report_id', 'client_uuid', name='uq_finding_client_uuid')
    )
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_findings_client_uuid'), ['client_uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_inspection_item_id'), ['inspection_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_roof_component_id'), ['roof_component_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_service_report_id'), ['service_report_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_status'), ['status'], unique=False)

    op.create_table('service_report_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_report_id', sa.Integer(), nullable=False),
    sa.Column('inspection_item_id', sa.Integer(), nullable=True),
    sa.Column('finding_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('caption', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='100', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_employee_id', sa.Integer(), nullable=True),
    sa.Column('client_uuid', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['created_by_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ),
    sa.ForeignKeyConstraint(['inspection_item_id'], ['inspection_items.id'], ),
    sa.ForeignKeyConstraint(['service_report_id'], ['service_reports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_report_id', 'client_uuid', name='uq_service_report_photo_client_uuid')
    )
    with op.batch_alter_table('service_report_photos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_report_photos_client_uuid'), ['client_uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_report_photos_finding_id'), ['finding_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_report_photos_inspection_item_id'), ['inspection_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_report_photos_service_report_id'), ['service_report_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_report_photos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_report_photos_service_report_id'))
        batch_op.drop_index(batch_op.f('ix_service_report_photos_inspection_item_id'))
        batch_op.drop_index(batch_op.f('ix_service_report_photos_finding_id'))
        batch_op.drop_index(batch_op.f('ix_service_report_photos_client_uuid'))

    op.drop_table('service_report_photos')
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_findings_status'))
        batch_op.drop_index(batch_op.f('ix_findings_service_report_id'))
        batch_op.drop_index(batch_op.f('ix_findings_roof_component_id'))
        batch_op.drop_index(batch_op.f('ix_findings_inspection_item_id'))
        batch_op.drop_index(batch_op.f('ix_findings_client_uuid'))

    op.drop_table('findings')
    # ### end Alembic commands ###
