"""maengel_neue_frist -- neue Beseitigungsfrist beim Eintrag "zurück auf offen" (seit 1.8.55, Stufe 2c-2c, Punkt 0)

- defect_events.due_on: nullable Datum. Gesetzt nur bei "zurück auf offen", und nur, wenn das Büro eine neue Frist angibt
  (app/defects.py::set_status()). Vorhandene Einträge bleiben leer; die aktuelle Frist eines Mangels ist die des letzten
  Eintrags mit einer, sonst die beim Erfassen (current_due()).
- Im gebundenen Inhalt des Eintrags steht "due_on" nur, wenn gesetzt -- die Prüfsummen aller vorhandenen Einträge bleiben
  unverändert gültig, ohne neue Fassung des Prüfsummenformats.

downgrade(): verweigert, solange ein Eintrag eine neue Frist trägt -- sie ginge verloren, und der Eintrag passte danach
nicht mehr zu seiner Prüfsumme (1.8.54 kennt die Frist im Inhalt nicht). Ohne solche Einträge entfernt er die Spalte.

Revision ID: 90a5ff1e1714
Revises: d5479410d4ff
Create Date: 2026-10-05 14:45:40.383562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90a5ff1e1714'
down_revision = 'd5479410d4ff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('defect_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_on', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    count = op.get_bind().execute(sa.text("SELECT COUNT(*) FROM defect_events WHERE due_on IS NOT NULL")).scalar()
    if count:
        raise RuntimeError(f"Downgrade verweigert: {count} Einträge im Verlauf von Mängeln tragen eine neue "
                           "Beseitigungsfrist -- sie ginge verloren, und die Einträge passten nicht mehr zu ihrer Prüfsumme.")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('defect_events', schema=None) as batch_op:
        batch_op.drop_column('due_on')

    # ### end Alembic commands ###
