"""abnahme_pruefsummenformat -- Fassung des Prüfsummenformats und Siegel des Verwerfens an der Abnahme (seit 1.8.48)

- order_acceptances.checksum_format: NOT NULL, server_default 1 -- jeder vorhandene Eintrag bleibt in Fassung 1, seine
  Prüfsumme wird nicht neu berechnet (Betreibervorgabe 2c-2a, Punkt 0). Neue Einträge schreibt der Code in Fassung 2
  (die Fassung steht dann im gebundenen Inhalt).
- order_acceptances.discard_sha256: Siegel des Verwerfens (Prüfsumme des Inhalts, Zeitpunkt, Name, Begründung). Vor
  dem Update verworfene Einträge bleiben ohne -- die Anzeige sagt "vor 1.8.48 erfasst, ohne Prüfsumme".

downgrade(): bricht ab, solange ein Eintrag der Fassung 2 oder ein Siegel besteht -- der Code von 1.8.47 rechnete
Fassung 2 ohne die Fassung im Inhalt nach und meldete jeden solchen Eintrag als "weicht ab".

Revision ID: 9c5a97bc71ef
Revises: 1dcea6473427
Create Date: 2026-10-05 07:39:47.692203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c5a97bc71ef'
down_revision = '1dcea6473427'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_acceptances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checksum_format', sa.Integer(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('discard_sha256', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    bind = op.get_bind()
    counts = {
        "Abnahmen in Prüfsummenformat 2": bind.execute(sa.text(
            "SELECT COUNT(*) FROM order_acceptances WHERE checksum_format >= 2")).scalar(),
        "versiegelte Verwerfen": bind.execute(sa.text(
            "SELECT COUNT(*) FROM order_acceptances WHERE discard_sha256 IS NOT NULL")).scalar(),
    }
    lost = ", ".join(f"{n} {label}" for label, n in counts.items() if n)
    if lost:
        raise RuntimeError(f"Downgrade verweigert: {lost} -- 1.8.47 könnte sie nicht mehr prüfen.")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_acceptances', schema=None) as batch_op:
        batch_op.drop_column('discard_sha256')
        batch_op.drop_column('checksum_format')

    # ### end Alembic commands ###
