"""checklisten baukasten

Seit 1.8.0 (Modul "checklisten", siehe docs/archiv/modul-checklisten.md): zehn neue Tabellen,
keine Änderung an bestehenden -- deshalb auch kein Datenrisiko auf einem gefüllten Bestand.
Vorlagen mit Fassungen (checklist_templates/_versions/_fields/_field_options/_rules) und
ausgefüllte Checklisten (checklists/_answers/_answer_selections/_attachments/
_rule_executions). downgrade() entfernt ausschließlich diese Tabellen wieder.

Revision ID: 9d6f31f78b88
Revises: cecb35eb85f8
Create Date: 2026-09-29 10:08:56.865974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d6f31f78b88'
down_revision = 'cecb35eb85f8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checklist_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('purpose', sa.String(length=40), server_default='allgemein', nullable=False),
    sa.Column('context_order', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('context_property', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('context_asset', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('context_company', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('field_readable', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='100', nullable=False),
    sa.Column('archived', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('checklist_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checklist_templates_archived'), ['archived'], unique=False)

    op.create_table('checklist_template_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='entwurf', nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('published_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['published_by_user_id'], ['app_users.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['checklist_templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'version_no', name='uq_checklist_template_version_no')
    )
    with op.batch_alter_table('checklist_template_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checklist_template_versions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_checklist_template_versions_template_id'), ['template_id'], unique=False)

    op.create_table('checklist_template_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('field_key', sa.String(length=80), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='100', nullable=False),
    sa.Column('group_name', sa.String(length=120), nullable=True),
    sa.Column('field_type', sa.String(length=30), nullable=False),
    sa.Column('label', sa.String(length=500), nullable=False),
    sa.Column('help_text', sa.Text(), nullable=True),
    sa.Column('required', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('allow_na', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('multiline', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('multiple', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('min_value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('max_value', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('decimals', sa.Integer(), nullable=True),
    sa.Column('min_count', sa.Integer(), nullable=True),
    sa.Column('max_count', sa.Integer(), nullable=True),
    sa.Column('prefill_now', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('signer_label', sa.String(length=80), nullable=True),
    sa.Column('is_system', sa.Boolean(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['checklist_template_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id', 'field_key', name='uq_checklist_template_field_key')
    )
    with op.batch_alter_table('checklist_template_fields', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checklist_template_fields_version_id'), ['version_id'], unique=False)

    op.create_table('checklist_template_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('field_key', sa.String(length=80), nullable=True),
    sa.Column('operator', sa.String(length=20), nullable=False),
    sa.Column('operand', sa.String(length=160), nullable=True),
    sa.Column('task_title', sa.String(length=255), nullable=False),
    sa.Column('task_description', sa.Text(), nullable=True),
    sa.Column('task_priority', sa.String(length=30), server_default='normal', nullable=False),
    sa.Column('due_in_days', sa.Integer(), nullable=True),
    sa.Column('assignee_mode', sa.String(length=30), server_default='rolle', nullable=False),
    sa.Column('min_visible_role', sa.String(length=30), server_default='buero_auftrag', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='100', nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['checklist_template_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('checklist_template_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checklist_template_rules_version_id'), ['version_id'], unique=False)

    op.create_table('checklist_template_field_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('option_key', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='100', nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['checklist_template_fields.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('field_id', 'option_key', name='uq_checklist_field_option_key')
    )
    with op.batch_alter_table('checklist_template_field_options', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checklist_template_field_options_field_id'), ['field_id'], unique=False)

    op.create_table('checklists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('template_version_id', sa.Integer(), nullable=False),
    sa.Column('template_label_snapshot', sa.String(length=160), nullable=False),
    sa.Column('context_type', sa.String(length=20), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('operational_asset_id', sa.Integer(), nullable=True),
    sa.Column('context_label_snapshot', sa.String(length=255), nullable=True),
    sa.Column('context_detail_snapshot', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='entwurf', nullable=False),
    sa.Column('created_by_employee_id', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('completed_by_employee_id', sa.Integer(), nullable=True),
    sa.Column('client_uuid', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['completed_by_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['created_by_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['app_users.id'], ),
    sa.ForeignKeyConstraint(['operational_asset_id'], ['operational_assets.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['checklist_templates.id'], ),
    sa.ForeignKeyConstraint(['template_version_id'], ['checklist_template_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_uuid', name='uq_checklist_client_uuid')
    )
    with op.batch_alter_table('checklists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checklists_context_type'), ['context_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_checklists_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_checklists_created_by_employee_id'), ['created_by_employee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_checklists_operational_asset_id'), ['operational_asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_checklists_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_checklists_property_id'), ['property_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_checklists_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_checklists_template_id'), ['template_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_checklists_template_version_id'), ['template_version_id'], unique=False)

    op.create_table('checklist_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('checklist_id', sa.Integer(), nullable=False),
    sa.Column('template_field_id', sa.Integer(), nullable=False),
    sa.Column('field_key', sa.String(length=80), nullable=False),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('value_number', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('value_date', sa.Date(), nullable=True),
    sa.Column('value_time', sa.Time(), nullable=True),
    sa.Column('value_datetime', sa.DateTime(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.Column('recorded_by_employee_id', sa.Integer(), nullable=True),
    sa.Column('client_uuid', sa.String(length=36), nullable=True),
    sa.Column('client_recorded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['checklist_id'], ['checklists.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['template_field_id'], ['checklist_template_fields.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('checklist_id', 'client_uuid', name='uq_checklist_answer_client_uuid'),
    sa.UniqueConstraint('checklist_id', 'template_field_id', name='uq_checklist_answer_field')
    )
    with op.batch_alter_table('checklist_answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checklist_answers_checklist_id'), ['checklist_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_checklist_answers_field_key'), ['field_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_checklist_answers_template_field_id'), ['template_field_id'], unique=False)

    op.create_table('checklist_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('checklist_id', sa.Integer(), nullable=False),
    sa.Column('template_field_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('signer_name', sa.String(length=160), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='100', nullable=False),
    sa.Column('created_by_employee_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('client_uuid', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['checklist_id'], ['checklists.id'], ),
    sa.ForeignKeyConstraint(['created_by_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['template_field_id'], ['checklist_template_fields.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('checklist_id', 'client_uuid', name='uq_checklist_attachment_client_uuid')
    )
    with op.batch_alter_table('checklist_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checklist_attachments_checklist_id'), ['checklist_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_checklist_attachments_template_field_id'), ['template_field_id'], unique=False)

    op.create_table('checklist_rule_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('checklist_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['checklist_id'], ['checklists.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['checklist_template_rules.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('checklist_id', 'rule_id', name='uq_checklist_rule_execution')
    )
    with op.batch_alter_table('checklist_rule_executions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checklist_rule_executions_checklist_id'), ['checklist_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_checklist_rule_executions_rule_id'), ['rule_id'], unique=False)

    op.create_table('checklist_answer_selections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('option_key', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['checklist_answers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('answer_id', 'option_key', name='uq_checklist_answer_selection')
    )
    with op.batch_alter_table('checklist_answer_selections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checklist_answer_selections_answer_id'), ['answer_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklist_answer_selections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checklist_answer_selections_answer_id'))

    op.drop_table('checklist_answer_selections')
    with op.batch_alter_table('checklist_rule_executions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checklist_rule_executions_rule_id'))
        batch_op.drop_index(batch_op.f('ix_checklist_rule_executions_checklist_id'))

    op.drop_table('checklist_rule_executions')
    with op.batch_alter_table('checklist_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checklist_attachments_template_field_id'))
        batch_op.drop_index(batch_op.f('ix_checklist_attachments_checklist_id'))

    op.drop_table('checklist_attachments')
    with op.batch_alter_table('checklist_answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checklist_answers_template_field_id'))
        batch_op.drop_index(batch_op.f('ix_checklist_answers_field_key'))
        batch_op.drop_index(batch_op.f('ix_checklist_answers_checklist_id'))

    op.drop_table('checklist_answers')
    with op.batch_alter_table('checklists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checklists_template_version_id'))
        batch_op.drop_index(batch_op.f('ix_checklists_template_id'))
        batch_op.drop_index(batch_op.f('ix_checklists_status'))
        batch_op.drop_index(batch_op.f('ix_checklists_property_id'))
        batch_op.drop_index(batch_op.f('ix_checklists_order_id'))
        batch_op.drop_index(batch_op.f('ix_checklists_operational_asset_id'))
        batch_op.drop_index(batch_op.f('ix_checklists_created_by_employee_id'))
        batch_op.drop_index(batch_op.f('ix_checklists_created_at'))
        batch_op.drop_index(batch_op.f('ix_checklists_context_type'))

    op.drop_table('checklists')
    with op.batch_alter_table('checklist_template_field_options', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checklist_template_field_options_field_id'))

    op.drop_table('checklist_template_field_options')
    with op.batch_alter_table('checklist_template_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checklist_template_rules_version_id'))

    op.drop_table('checklist_template_rules')
    with op.batch_alter_table('checklist_template_fields', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checklist_template_fields_version_id'))

    op.drop_table('checklist_template_fields')
    with op.batch_alter_table('checklist_template_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checklist_template_versions_template_id'))
        batch_op.drop_index(batch_op.f('ix_checklist_template_versions_status'))

    op.drop_table('checklist_template_versions')
    with op.batch_alter_table('checklist_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checklist_templates_archived'))

    op.drop_table('checklist_templates')
    # ### end Alembic commands ###
