"""Briefbogen-Hintergrund und Kundenadresse/Meta-Tabelle getrennt

Revision ID: 9e959412c279
Revises: 58e4e0719407
Create Date: 2026-09-05 10:10:43.406500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e959412c279'
down_revision = '58e4e0719407'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_layout_backgrounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=20), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_layout_backgrounds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_layout_backgrounds_document_type'), ['document_type'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_layout_backgrounds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_layout_backgrounds_document_type'))

    op.drop_table('document_layout_backgrounds')
    # ### end Alembic commands ###
