"""address import: customer/supplier/property fields, import_runs, imported_addresses

Revision ID: 9ff6f4131413
Revises: 14b130f9c315
Create Date: 2026-09-12 13:58:38.143406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ff6f4131413'
down_revision = '14b130f9c315'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_filename', sa.String(length=255), nullable=False),
    sa.Column('created_by_employee_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('row_count_total', sa.Integer(), nullable=False),
    sa.Column('row_count_customers', sa.Integer(), nullable=False),
    sa.Column('row_count_suppliers', sa.Integer(), nullable=False),
    sa.Column('row_count_unassigned', sa.Integer(), nullable=False),
    sa.Column('row_count_skipped_duplicates', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reverted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imported_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_run_id', sa.Integer(), nullable=True),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('legacy_address_number', sa.String(length=50), nullable=True),
    sa.Column('customer_number_raw', sa.String(length=50), nullable=True),
    sa.Column('supplier_number_raw', sa.String(length=50), nullable=True),
    sa.Column('salutation', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=80), nullable=True),
    sa.Column('first_name', sa.String(length=120), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('street', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=80), nullable=True),
    sa.Column('fax', sa.String(length=80), nullable=True),
    sa.Column('mobile', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('email_2', sa.String(length=255), nullable=True),
    sa.Column('classification', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('validation_notes', sa.Text(), nullable=True),
    sa.Column('resolution', sa.String(length=30), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_customer_id', sa.Integer(), nullable=True),
    sa.Column('created_supplier_id', sa.Integer(), nullable=True),
    sa.Column('created_property_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['created_property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['created_supplier_id'], ['suppliers.id'], ),
    sa.ForeignKeyConstraint(['import_run_id'], ['import_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('imported_addresses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_imported_addresses_import_run_id'), ['import_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_imported_addresses_legacy_address_number'), ['legacy_address_number'], unique=False)

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salutation', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('title', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('first_name', sa.String(length=120), nullable=True))
        # last_name ist das neue Pflichtfeld -- die Tabelle ist bereits gefüllt (Regel 1), daher
        # zunächst mit server_default='' anlegen, per Backfill befüllen, Default danach wieder
        # entfernen (kein dauerhafter Fallback-Wert für künftige Zeilen gewollt).
        batch_op.add_column(sa.Column('last_name', sa.String(length=255), server_default='', nullable=False))
        batch_op.add_column(sa.Column('country', sa.String(length=120), server_default='Deutschland', nullable=False))
        batch_op.add_column(sa.Column('email_2', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('mobile', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('legacy_address_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('import_run_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_customers_import_run_id'), ['import_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_legacy_address_number'), ['legacy_address_number'], unique=False)
        batch_op.create_unique_constraint('uq_customer_legacy_address_number', ['legacy_address_number'])
        batch_op.create_foreign_key('fk_customers_import_run_id', 'import_runs', ['import_run_id'], ['id'])

    # Backfill: last_name trägt für Bestandskunden zunächst den kompletten bisherigen name-Wert
    # (salutation/title/first_name bleiben leer) -- app.crm.compose_customer_name() setzt name
    # aus genau diesen Teilen zusammen, ein bestehender Kunde zeigt danach exakt denselben
    # Namen wie vorher, siehe CLAUDE.md "Adressimport aus dem Altsystem".
    op.execute("UPDATE customers SET last_name = name")

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.alter_column('last_name', server_default=None)

    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.String(length=120), nullable=True))

    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('legacy_address_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('import_run_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_suppliers_import_run_id'), ['import_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_suppliers_legacy_address_number'), ['legacy_address_number'], unique=False)
        batch_op.create_unique_constraint('uq_supplier_legacy_address_number', ['legacy_address_number'])
        batch_op.create_foreign_key('fk_suppliers_import_run_id', 'import_runs', ['import_run_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_constraint('fk_suppliers_import_run_id', type_='foreignkey')
        batch_op.drop_constraint('uq_supplier_legacy_address_number', type_='unique')
        batch_op.drop_index(batch_op.f('ix_suppliers_legacy_address_number'))
        batch_op.drop_index(batch_op.f('ix_suppliers_import_run_id'))
        batch_op.drop_column('import_run_id')
        batch_op.drop_column('legacy_address_number')

    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_column('country')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_constraint('fk_customers_import_run_id', type_='foreignkey')
        batch_op.drop_constraint('uq_customer_legacy_address_number', type_='unique')
        batch_op.drop_index(batch_op.f('ix_customers_legacy_address_number'))
        batch_op.drop_index(batch_op.f('ix_customers_import_run_id'))
        batch_op.drop_column('import_run_id')
        batch_op.drop_column('legacy_address_number')
        batch_op.drop_column('mobile')
        batch_op.drop_column('email_2')
        batch_op.drop_column('country')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')
        batch_op.drop_column('title')
        batch_op.drop_column('salutation')

    with op.batch_alter_table('imported_addresses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_imported_addresses_legacy_address_number'))
        batch_op.drop_index(batch_op.f('ix_imported_addresses_import_run_id'))

    op.drop_table('imported_addresses')
    op.drop_table('import_runs')
    # ### end Alembic commands ###
