"""mobile field view: installer signature columns, mobile_settings

Revision ID: a1b7a145e5d5
Revises: f6f429b505f3
Create Date: 2026-09-10 15:59:08.895366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b7a145e5d5'
down_revision = 'f6f429b505f3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mobile_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shift_end_time', sa.Time(), server_default='19:00:00', nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('installer_signature_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('installer_signature_name', sa.String(length=160), nullable=True))
        batch_op.add_column(sa.Column('installer_signed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_reports', schema=None) as batch_op:
        batch_op.drop_column('installer_signed_at')
        batch_op.drop_column('installer_signature_name')
        batch_op.drop_column('installer_signature_path')

    op.drop_table('mobile_settings')
    # ### end Alembic commands ###
