"""add user dashboard widgets table

Revision ID: ad3efb9bf522
Revises: 609b69008de8
Create Date: 2026-09-08 00:06:40.555416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad3efb9bf522'
down_revision = '609b69008de8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_dashboard_widgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('widget_key', sa.String(length=60), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'widget_key', name='uq_user_dashboard_widget')
    )
    with op.batch_alter_table('user_dashboard_widgets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_dashboard_widgets_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_dashboard_widgets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_dashboard_widgets_user_id'))

    op.drop_table('user_dashboard_widgets')
    # ### end Alembic commands ###
