"""checklisten_abschluss_kopie -- Abschließen legt eine feste Kopie mit Prüfsumme ab (seit 1.8.15)

Zwei Spalten an checklists, nullable, keine Datenänderung beim Upgrade:
- sealed_content: feste Kopie ALLER Felder samt Unterschriften im Moment des Abschließens
  (kanonisches JSON, app/checklists.py::completion_content()).
- content_sha256: SHA-256 genau dieser Zeichenkette.

Bereits abgeschlossene Checklisten bekommen keine Kopie nachgetragen: der Inhalt im Moment des
Abschlusses ist nicht nachweisbar bekannt, eine nachgerechnete Summe würde den heutigen Stand als
damaligen bescheinigen. NULL heißt "ohne Prüfsumme abgeschlossen" (Seite und PDF sagen das).

downgrade(): entfernt beide Spalten, damit auch die Kopien der seither abgeschlossenen
Checklisten -- die Checklisten selbst bleiben unverändert abgeschlossen.

Revision ID: af9cd6b4e543
Revises: 05a080705f2c
Create Date: 2026-09-30 09:00:44.614123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af9cd6b4e543'
down_revision = '05a080705f2c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_sha256', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('sealed_content', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklists', schema=None) as batch_op:
        batch_op.drop_column('sealed_content')
        batch_op.drop_column('content_sha256')

    # ### end Alembic commands ###
