"""service_report_assets_und_selectable_in_reports

Revision ID: b2226e22b9f0
Revises: ed896599a211
Create Date: 2026-09-18 08:26:46.985671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2226e22b9f0'
down_revision = 'ed896599a211'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_report_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_report_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('asset_name_snapshot', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='100', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_employee_id', sa.Integer(), nullable=True),
    sa.Column('client_uuid', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['operational_assets.id'], ),
    sa.ForeignKeyConstraint(['created_by_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['service_report_id'], ['service_reports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_report_id', 'client_uuid', name='uq_service_report_asset_client_uuid')
    )
    with op.batch_alter_table('service_report_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_report_assets_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_report_assets_client_uuid'), ['client_uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_report_assets_service_report_id'), ['service_report_id'], unique=False)

    with op.batch_alter_table('operational_assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selectable_in_reports', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operational_assets', schema=None) as batch_op:
        batch_op.drop_column('selectable_in_reports')

    with op.batch_alter_table('service_report_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_report_assets_service_report_id'))
        batch_op.drop_index(batch_op.f('ix_service_report_assets_client_uuid'))
        batch_op.drop_index(batch_op.f('ix_service_report_assets_asset_id'))

    op.drop_table('service_report_assets')
    # ### end Alembic commands ###
