"""checklisten_zweck_folgen -- Zweck an der Fassung, Folgetabelle (seit 1.8.16)

- checklist_template_versions.purpose (NOT NULL, server_default "allgemein"): der beim
  Veröffentlichen eingefrorene Zweck. Beim Upgrade bekommt jede vorhandene Fassung den Zweck
  ihrer Vorlage (checklist_templates.purpose, seit 1.8.0 vorhanden, bisher immer "allgemein") --
  so, wie er beim Veröffentlichen gegolten hat.
- checklist_follow_ups: Folgen des Abschlusses nach Zweck, eindeutig je (Checkliste,
  Folgeschlüssel), zugleich Idempotenzsperre (Muster checklist_rule_executions). Leer beim Upgrade.

downgrade(): entfernt Tabelle und Spalte. checklist_templates.purpose bleibt unverändert stehen
-- das ist der Zustand vor dieser Migration.

Revision ID: b3a6e4cb70fc
Revises: 803d94127c12
Create Date: 2026-09-30 10:03:02.135426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3a6e4cb70fc'
down_revision = '803d94127c12'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checklist_follow_ups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('checklist_id', sa.Integer(), nullable=False),
    sa.Column('follow_up_key', sa.String(length=80), nullable=False),
    sa.Column('target_type', sa.String(length=40), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='ausstehend', nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['checklist_id'], ['checklists.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('checklist_id', 'follow_up_key', name='uq_checklist_follow_up_key')
    )
    with op.batch_alter_table('checklist_follow_ups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checklist_follow_ups_checklist_id'), ['checklist_id'], unique=False)

    with op.batch_alter_table('checklist_template_versions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purpose', sa.String(length=40), server_default='allgemein', nullable=False))

    # ### end Alembic commands ###

    # Zweck der Vorlage in jede vorhandene Fassung (SQLite und PostgreSQL gleichermaßen).
    op.execute(
        "UPDATE checklist_template_versions SET purpose = ("
        "SELECT t.purpose FROM checklist_templates t WHERE t.id = checklist_template_versions.template_id)"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklist_template_versions', schema=None) as batch_op:
        batch_op.drop_column('purpose')

    with op.batch_alter_table('checklist_follow_ups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checklist_follow_ups_checklist_id'))

    op.drop_table('checklist_follow_ups')
    # ### end Alembic commands ###
