"""versandprotokoll_und_ablage -- Ablage versendeter Dokumente und Versandprotokoll (seit 1.8.17)

- sent_documents: je versendetem PDF eine Zeile (Dokumentart/-ID, Dateiname, SHA-256, Größe,
  Zeitpunkt, Benutzer); die Datei selbst liegt unter DACHKONZEPTE_SENT_DOCUMENT_ROOT.
- email_dispatches: je Versandauftrag eine Zeile (Schlüssel, eigene Kennung, Status, Kanal,
  Empfänger, Betreff, Verweis auf die Ablage, Fehlerklasse). Beide leer beim Upgrade.

downgrade(): entfernt beide Tabellen -- aber nur, solange sie leer sind. Stehen Einträge darin,
bricht er ab: sonst gingen Prüfsummen und Nachweis jedes bisherigen Versands verloren (die Dateien
blieben ohne Zuordnung liegen). Wer wirklich zurück muss, sichert vorher und leert die Tabellen
bewusst von Hand.

Revision ID: b414df7c7744
Revises: b3a6e4cb70fc
Create Date: 2026-09-30 15:29:27.077182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b414df7c7744'
down_revision = 'b3a6e4cb70fc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sent_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=20), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('document_number', sa.String(length=80), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_by_name', sa.String(length=160), server_default='System', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_filename')
    )
    with op.batch_alter_table('sent_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sent_documents_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sent_documents_document_type'), ['document_type'], unique=False)

    op.create_table('email_dispatches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dispatch_key', sa.String(length=80), nullable=False),
    sa.Column('message_ref', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='in_arbeit', nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('document_type', sa.String(length=20), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('document_number', sa.String(length=80), nullable=True),
    sa.Column('to_recipients', sa.Text(), nullable=False),
    sa.Column('cc_recipients', sa.Text(), nullable=True),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('sent_document_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_by_name', sa.String(length=160), server_default='System', nullable=False),
    sa.Column('error_class', sa.String(length=120), nullable=True),
    sa.Column('error_code', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['sent_document_id'], ['sent_documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dispatch_key'),
    sa.UniqueConstraint('message_ref')
    )
    with op.batch_alter_table('email_dispatches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_dispatches_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_dispatches_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_dispatches_document_type'), ['document_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_dispatches_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    bind = op.get_bind()
    for table in ("email_dispatches", "sent_documents"):
        count = bind.execute(sa.text(f"SELECT COUNT(*) FROM {table}")).scalar()
        if count:
            raise RuntimeError(
                f"Downgrade abgebrochen: {table} enthält {count} Einträge (Versandnachweis). "
                "Vorher sichern und bewusst leeren, siehe Docstring dieser Migration."
            )
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_dispatches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_dispatches_status'))
        batch_op.drop_index(batch_op.f('ix_email_dispatches_document_type'))
        batch_op.drop_index(batch_op.f('ix_email_dispatches_document_id'))
        batch_op.drop_index(batch_op.f('ix_email_dispatches_created_at'))

    op.drop_table('email_dispatches')
    with op.batch_alter_table('sent_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sent_documents_document_type'))
        batch_op.drop_index(batch_op.f('ix_sent_documents_document_id'))

    op.drop_table('sent_documents')
    # ### end Alembic commands ###
