"""roof layer types and layers

Revision ID: b8adafd0b997
Revises: 8c6c6860cc71
Create Date: 2026-09-09 15:34:47.142084

"""
from datetime import datetime

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8adafd0b997'
down_revision = '8c6c6860cc71'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roof_layer_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('roof_type', sa.String(length=80), nullable=True),
    sa.Column('option_group', sa.String(length=80), nullable=True),
    sa.Column('has_thickness', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='100', nullable=False),
    sa.Column('active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    with op.batch_alter_table('roof_layer_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roof_layer_types_active'), ['active'], unique=False)

    # Seed der Schichttypen (Muster wie Migration 623c88dc1bae für maintenance_windows) --
    # eine echte Tabelle, kein SettingOptionGroup, deshalb keine Selbst-Seed-Mechanik.
    #
    # Gründach bekommt bewusst dieselben 7 Schichten wie Flachdach UNTER EIGENEN key-Werten
    # erneut, statt sie über roof_type IS NULL zu teilen: roof_type ist ein einzelnes Feld je
    # Schichttyp, kein Mehrfachbezug. NULL würde "gilt für jeden Dachtyp" bedeuten -- ein
    # Steildach bekäme dann fälschlich auch Dampfsperre/Abdichtung angezeigt. Ein Gründach ist
    # baulich ein Flachdach mit zusätzlichen Schichten obendrauf; eigene, redundante Zeilen je
    # Dachtyp sind die einzige Lösung, die jeden Dachtyp korrekt isoliert. Bekannte Schwachstelle
    # dieser Redundanz: siehe CLAUDE.md, Abschnitt "Bekannte, bewusst offene Punkte".
    now = datetime.utcnow()
    roof_layer_types = sa.table(
        'roof_layer_types',
        sa.column('id', sa.Integer), sa.column('key', sa.String), sa.column('label', sa.String),
        sa.column('roof_type', sa.String), sa.column('option_group', sa.String),
        sa.column('has_thickness', sa.Boolean), sa.column('sort_order', sa.Integer),
        sa.column('active', sa.Boolean),
        sa.column('created_at', sa.DateTime), sa.column('updated_at', sa.DateTime),
    )

    def _row(id_, key, label, roof_type, option_group, has_thickness, sort_order):
        return {
            'id': id_, 'key': key, 'label': label, 'roof_type': roof_type, 'option_group': option_group,
            'has_thickness': has_thickness, 'sort_order': sort_order, 'active': True,
            'created_at': now, 'updated_at': now,
        }

    rows = [
        # Steildach
        _row(1, 'steildach_traglage', 'Traglage', 'Steildach', 'layer_traglage', False, 10),
        _row(2, 'steildach_unterspannbahn', 'Unterspannbahn', 'Steildach', 'layer_unterspannbahn', False, 20),
        _row(3, 'steildach_aufsparrendaemmung', 'Aufsparrendämmung', 'Steildach', 'layer_daemmung', True, 30),
        _row(4, 'steildach_zwischensparrendaemmung', 'Zwischensparrendämmung', 'Steildach', 'layer_daemmung', True, 40),
        _row(5, 'steildach_untersparrendaemmung', 'Untersparrendämmung', 'Steildach', 'layer_daemmung', True, 50),
        _row(6, 'steildach_konterlattung', 'Konterlattung', 'Steildach', None, False, 60),
        _row(7, 'steildach_dachlattung', 'Dachlattung', 'Steildach', None, False, 70),
        # Flachdach
        _row(8, 'flachdach_traglage', 'Traglage', 'Flachdach', 'layer_traglage', False, 10),
        _row(9, 'flachdach_dampfsperre', 'Dampfsperre', 'Flachdach', 'layer_dampfsperre', False, 20),
        _row(10, 'flachdach_daemmung', 'Dämmung', 'Flachdach', 'layer_daemmung', True, 30),
        _row(11, 'flachdach_gefaelledaemmung', 'Gefälledämmung', 'Flachdach', 'layer_daemmung', True, 40),
        _row(12, 'flachdach_trennlage', 'Trennlage', 'Flachdach', None, False, 50),
        _row(13, 'flachdach_abdichtung', 'Abdichtung', 'Flachdach', 'layer_abdichtung', False, 60),
        _row(14, 'flachdach_oberflaechenschutz', 'Oberflächenschutz', 'Flachdach', 'layer_oberflaeche', False, 70),
        # Gründach (7 wie Flachdach, siehe Kommentar oben, + 4 zusätzliche)
        _row(15, 'gruendach_traglage', 'Traglage', 'Gründach', 'layer_traglage', False, 10),
        _row(16, 'gruendach_dampfsperre', 'Dampfsperre', 'Gründach', 'layer_dampfsperre', False, 20),
        _row(17, 'gruendach_daemmung', 'Dämmung', 'Gründach', 'layer_daemmung', True, 30),
        _row(18, 'gruendach_gefaelledaemmung', 'Gefälledämmung', 'Gründach', 'layer_daemmung', True, 40),
        _row(19, 'gruendach_trennlage', 'Trennlage', 'Gründach', None, False, 50),
        _row(20, 'gruendach_abdichtung', 'Abdichtung', 'Gründach', 'layer_abdichtung', False, 60),
        _row(21, 'gruendach_oberflaechenschutz', 'Oberflächenschutz', 'Gründach', 'layer_oberflaeche', False, 70),
        _row(22, 'gruendach_wurzelschutzbahn', 'Wurzelschutzbahn', 'Gründach', None, False, 80),
        _row(23, 'gruendach_draenschicht', 'Dränschicht', 'Gründach', None, False, 90),
        _row(24, 'gruendach_filtervlies', 'Filtervlies', 'Gründach', None, False, 100),
        _row(25, 'gruendach_substrat', 'Substrat', 'Gründach', None, True, 110),
    ]
    op.bulk_insert(roof_layer_types, rows)

    op.create_table('roof_layers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roof_area_id', sa.Integer(), nullable=False),
    sa.Column('layer_type_id', sa.Integer(), nullable=False),
    sa.Column('present', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('execution', sa.String(length=160), nullable=True),
    sa.Column('thickness_mm', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['layer_type_id'], ['roof_layer_types.id'], ),
    sa.ForeignKeyConstraint(['roof_area_id'], ['roof_areas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('roof_area_id', 'layer_type_id', name='uq_roof_layer_area_type')
    )
    with op.batch_alter_table('roof_layers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roof_layers_layer_type_id'), ['layer_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_roof_layers_roof_area_id'), ['roof_area_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roof_layers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roof_layers_roof_area_id'))
        batch_op.drop_index(batch_op.f('ix_roof_layers_layer_type_id'))

    op.drop_table('roof_layers')
    with op.batch_alter_table('roof_layer_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roof_layer_types_active'))

    op.drop_table('roof_layer_types')
    # ### end Alembic commands ###
