"""E-Mail-Versand fuer Angebote

Revision ID: b9b377efedd0
Revises: 3eb9f52b38ab
Create Date: 2026-09-07 12:09:22.023676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9b377efedd0'
down_revision = '3eb9f52b38ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_sent_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('email_sent_to', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quotes', schema=None) as batch_op:
        batch_op.drop_column('email_sent_to')
        batch_op.drop_column('email_sent_at')

    # ### end Alembic commands ###
