"""dachflaechen und bauteile

Revision ID: bfe5e08483b0
Revises: 8adb7e406857
Create Date: 2026-09-09 09:14:09.630105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfe5e08483b0'
down_revision = '8adb7e406857'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roof_areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('roof_type', sa.String(length=80), nullable=True),
    sa.Column('covering', sa.String(length=120), nullable=True),
    sa.Column('pitch_degrees', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('area_sqm', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('build_up', sa.Text(), nullable=True),
    sa.Column('insulation', sa.String(length=255), nullable=True),
    sa.Column('last_renovation', sa.Date(), nullable=True),
    sa.Column('contractor', sa.String(length=255), nullable=True),
    sa.Column('warranty_until', sa.Date(), nullable=True),
    sa.Column('sketch_path', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('archived', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roof_areas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roof_areas_archived'), ['archived'], unique=False)
        batch_op.create_index(batch_op.f('ix_roof_areas_property_id'), ['property_id'], unique=False)

    op.create_table('roof_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roof_area_id', sa.Integer(), nullable=False),
    sa.Column('component_type', sa.String(length=80), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('sketch_x', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('sketch_y', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('archived', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['roof_area_id'], ['roof_areas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('roof_components', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roof_components_archived'), ['archived'], unique=False)
        batch_op.create_index(batch_op.f('ix_roof_components_roof_area_id'), ['roof_area_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roof_components', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roof_components_roof_area_id'))
        batch_op.drop_index(batch_op.f('ix_roof_components_archived'))

    op.drop_table('roof_components')
    with op.batch_alter_table('roof_areas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roof_areas_property_id'))
        batch_op.drop_index(batch_op.f('ix_roof_areas_archived'))

    op.drop_table('roof_areas')
    # ### end Alembic commands ###
