"""outlook calendar sync retry marker

Revision ID: c137c16e9a5c
Revises: 6573d677bc1d
Create Date: 2026-09-26 11:01:13.510623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c137c16e9a5c'
down_revision = '6573d677bc1d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('outlook_synced_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.drop_column('outlook_synced_at')

    # ### end Alembic commands ###
