"""Mustervorgaenge is_template

Revision ID: c208d96579ce
Revises: 26c9609a8d41
Create Date: 2026-09-07 13:04:26.539948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c208d96579ce'
down_revision = '26c9609a8d41'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_template', sa.Boolean(), server_default='0', nullable=False))
        batch_op.create_index(batch_op.f('ix_projects_is_template'), ['is_template'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_is_template'))
        batch_op.drop_column('is_template')

    # ### end Alembic commands ###
