"""sidebar logo height

Revision ID: c327ff4ad332
Revises: 1b55170709a6
Create Date: 2026-09-14 10:45:27.009453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c327ff4ad332'
down_revision = '1b55170709a6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('general_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sidebar_logo_height_px', sa.Integer(), server_default='48', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('general_settings', schema=None) as batch_op:
        batch_op.drop_column('sidebar_logo_height_px')

    # ### end Alembic commands ###
