"""operational assets stufe 2 qr and public base url

Revision ID: ccb5c4c0915b
Revises: 5917bb099776
Create Date: 2026-09-17 21:24:46.440562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccb5c4c0915b'
down_revision = '5917bb099776'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('general_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_base_url', sa.String(length=255), nullable=True))

    with op.batch_alter_table('operational_assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('article_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('product_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('usage_notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operational_assets', schema=None) as batch_op:
        batch_op.drop_column('usage_notes')
        batch_op.drop_column('product_url')
        batch_op.drop_column('article_number')

    with op.batch_alter_table('general_settings', schema=None) as batch_op:
        batch_op.drop_column('public_base_url')

    # ### end Alembic commands ###
