"""unterzeichner_person -- Person und Funktion beim Unterzeichner "Auftraggeber laut Auftrag" (seit 1.8.59, Stufe 2c-2d)

- checklist_attachments.signer_person (Pflicht beim Unterschreiben für den Auftraggeber, nullable in der Tabelle) und
  signer_function (optional). Vorhandene Unterschriften bleiben leer; ihr Siegel enthält beides nicht und bleibt gültig
  (im Siegel stehen Person und Funktion nur, wenn gesetzt -- app/checklists.py::signer_content()).

downgrade(): verweigert, sobald eine Unterschrift eine Person trägt -- sie ginge verloren, und das Siegel passte nicht mehr.

Revision ID: cd0d94c87f0c
Revises: 5e562a4a172b
Create Date: 2026-10-05

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd0d94c87f0c'
down_revision = '5e562a4a172b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklist_attachments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signer_person', sa.String(length=160), nullable=True))
        batch_op.add_column(sa.Column('signer_function', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    count = op.get_bind().execute(sa.text(
        "SELECT COUNT(*) FROM checklist_attachments WHERE signer_person IS NOT NULL OR signer_function IS NOT NULL")).scalar()
    if count:
        raise RuntimeError(f"Downgrade verweigert: {count} Unterschriften tragen die unterschreibende Person -- sie ginge "
                           "verloren, und das Siegel passte nicht mehr.")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklist_attachments', schema=None) as batch_op:
        batch_op.drop_column('signer_function')
        batch_op.drop_column('signer_person')

    # ### end Alembic commands ###
