"""group member individually changed

Revision ID: cecb35eb85f8
Revises: 2f5de21f11b8
Create Date: 2026-09-29 09:33:37.378842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cecb35eb85f8'
down_revision = '2f5de21f11b8'
branch_labels = None
depends_on = None


# Bestandsgruppen: nachträglich markieren, was erkennbar schon einzeln geändert wurde -- Datum,
# Auftrag oder Zeitart weicht vom Gruppenkopf ab; bei manuellen Gruppen zusätzlich die Stunden
# (bei Timer-Gruppen sind unterschiedliche Stunden durch eigene Pausen normal, kein Merkmal).
BACKFILL_SQL = """
UPDATE time_entry_group_members SET individually_changed_at = CURRENT_TIMESTAMP
WHERE id IN (
    SELECT m.id FROM time_entry_group_members m
    JOIN time_entry_groups g ON g.id = m.group_id
    JOIN time_entries e ON e.id = m.time_entry_id
    WHERE e.work_date <> g.work_date OR e.order_id <> g.order_id OR e.entry_type <> g.entry_type
       OR (g.mode = 'manual' AND e.hours <> g.hours)
)
"""


def upgrade() -> None:
    with op.batch_alter_table('time_entry_group_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('individually_changed_at', sa.DateTime(), nullable=True))
    op.execute(sa.text(BACKFILL_SQL))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_entry_group_members', schema=None) as batch_op:
        batch_op.drop_column('individually_changed_at')

    # ### end Alembic commands ###
