"""schlechtwetter zeitarten und abwesenheitskategorie

Revision ID: cf4fdf4905cd
Revises: 57062a31dba7
Create Date: 2026-09-19 09:11:20.149679

"""
from datetime import datetime

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf4fdf4905cd'
down_revision = '57062a31dba7'
branch_labels = None
depends_on = None


def seed_weather_time_entry_types(bind) -> None:
    """Ergänzt die beiden neuen Schlechtwetter-Zeitarten in einer bereits zuvor gesäten
    time_entry_types-Gruppe -- ensure_default_option_groups() (app/option_settings.py) füllt
    eine bereits existierende Gruppe nie nachträglich mit neuen Defaults auf ("Existierende
    Gruppen werden nicht wieder mit Defaults aufgefüllt"), das erweiterte DEFAULT_OPTION_GROUPS
    allein reicht für eine schon laufende Installation deshalb nicht -- Muster Migration
    257fb2967c93 (vierter Rahmen-Baustein für einen bereits gesäten Satz). Idempotent (prüft
    group_id+label vor dem Insert), kein Fehler bei erneutem Lauf. Existiert die Gruppe noch gar
    nicht (frische Installation ohne jeden Zugriff bisher), entsteht sie beim ersten Zugriff
    bereits mit allen sechs Werten aus DEFAULT_OPTION_GROUPS -- dann ist hier nichts zu tun."""
    group_id = bind.execute(
        sa.text("SELECT id FROM setting_option_groups WHERE group_key = 'time_entry_types'")
    ).scalar()
    if group_id is None:
        return
    now = datetime.utcnow()
    for sort_order, label, value in (
        (50, "Schlechtwetter Winter", "weather_winter"),
        (60, "Schlechtwetter Sommer", "weather_summer"),
    ):
        exists = bind.execute(
            sa.text("SELECT 1 FROM setting_options WHERE group_id = :gid AND label = :label"),
            {"gid": group_id, "label": label},
        ).first()
        if exists:
            continue
        bind.execute(
            sa.text(
                "INSERT INTO setting_options (group_id, label, value, sort_order, active, is_default, created_at, updated_at) "
                "VALUES (:gid, :label, :value, :sort_order, :active, :is_default, :now, :now)"
            ),
            {
                "gid": group_id, "label": label, "value": value, "sort_order": sort_order,
                "active": True, "is_default": False, "now": now,
            },
        )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_absence_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('absence_category', sa.String(length=20), server_default='unbekannt', nullable=False))
        batch_op.create_index(batch_op.f('ix_employee_absence_requests_absence_category'), ['absence_category'], unique=False)

    with op.batch_alter_table('employee_absences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('absence_category', sa.String(length=20), server_default='unbekannt', nullable=False))
        batch_op.create_index(batch_op.f('ix_employee_absences_absence_category'), ['absence_category'], unique=False)

    with op.batch_alter_table('time_tracking_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('datev_wage_type_weather_winter', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('datev_wage_type_weather_summer', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###

    seed_weather_time_entry_types(op.get_bind())


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_tracking_settings', schema=None) as batch_op:
        batch_op.drop_column('datev_wage_type_weather_summer')
        batch_op.drop_column('datev_wage_type_weather_winter')

    with op.batch_alter_table('employee_absences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_absences_absence_category'))
        batch_op.drop_column('absence_category')

    with op.batch_alter_table('employee_absence_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_absence_requests_absence_category'))
        batch_op.drop_column('absence_category')

    # ### end Alembic commands ###
