"""maengel_aufgabe_je_eintrag -- Aufgabe, die ein Eintrag im Verlauf eines Mangels angelegt hat (seit 1.8.54, Stufe 2c-2b)

- defect_events.task_id: nullable, ohne Fremdschlüssel (wie defects.task_id -- eine Aufgabe lässt sich löschen, der
  Eintrag bleibt). Gesetzt bei "beseitigt" ("Beseitigung abnehmen lassen") und "zurück auf offen" ("Mangel beseitigen"),
  app/defects.py::_append(). Vorhandene Einträge bleiben leer: ihre aktuelle Aufgabe ist die beim Erfassen.

downgrade(): entfernt die Spalte ohne Rückfrage. Verloren gehen nur die Verweise vom Eintrag auf seine Aufgabe; die
Aufgaben selbst bleiben (mit Verweis auf den Mangel in source_url), die Einträge bleiben gültig (die Spalte steht nicht im
gebundenen Inhalt). Nach dem Zurückgehen gilt wieder die Aufgabe beim Erfassen als die des Mangels.

Revision ID: d5479410d4ff
Revises: 6c7610e54ce3
Create Date: 2026-10-05 12:22:00.222926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5479410d4ff'
down_revision = '6c7610e54ce3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('defect_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('defect_events', schema=None) as batch_op:
        batch_op.drop_column('task_id')

    # ### end Alembic commands ###
