"""ai fundament settings and call log

Revision ID: d87d5bc04b69
Revises: 329725277349
Create Date: 2026-09-22 08:19:56.131348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd87d5bc04b69'
down_revision = '329725277349'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_call_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('caller', sa.String(length=80), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_type', sa.String(length=80), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_estimate', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_call_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_call_log_caller'), ['caller'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_call_log_occurred_at'), ['occurred_at'], unique=False)

    op.create_table('ai_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=True),
    sa.Column('api_base_url', sa.String(length=500), nullable=True),
    sa.Column('api_key_encrypted', sa.Text(), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_settings')
    with op.batch_alter_table('ai_call_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_call_log_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_ai_call_log_caller'))

    op.drop_table('ai_call_log')
    # ### end Alembic commands ###
