"""Adressbuch und Beteiligte am Projekt (seit 1.8.37, Stufe 2b, Runde 2b-2)

- Tabelle contacts: Person oder Firma (kind, server_default 'person'), Funktion, Telefon, Mobil, E-Mail,
  Adresse, archived (server_default falsch) -- das Adressbuch (app/contacts.py).
- Tabelle project_participants: Projekt -- Kontakt -- Rolle, eindeutig je (project_id, contact_id, role)
  (uq_project_participant), Häkchen copy_on_notices und authorized_recipient (server_default falsch),
  poa_* für die Vollmacht als Beleg (app/project_participants.py).
- Nur neue Tabellen, kein Bestand zu übernehmen.

downgrade(): bricht ab, solange eine der beiden Tabellen Zeilen hat -- sonst wären Adressbuch und
Beteiligte still weg (und die Belege unter DACHKONZEPTE_PARTICIPANT_FILE_ROOT ohne Zuordnung).

Revision ID: d99494185ce7
Revises: 71460718a43e
Create Date: 2026-10-02 08:13:58.244367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd99494185ce7'
down_revision = '71460718a43e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=10), server_default='person', nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=120), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('function', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=80), nullable=True),
    sa.Column('mobile', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('street', sa.String(length=255), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('archived', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contacts_archived'), ['archived'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_company_name'), ['company_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_contacts_last_name'), ['last_name'], unique=False)

    op.create_table('project_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('copy_on_notices', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('authorized_recipient', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('poa_stored_filename', sa.String(length=255), nullable=True),
    sa.Column('poa_original_filename', sa.String(length=255), nullable=True),
    sa.Column('poa_content_type', sa.String(length=100), nullable=True),
    sa.Column('poa_size_bytes', sa.Integer(), nullable=True),
    sa.Column('poa_sha256', sa.String(length=64), nullable=True),
    sa.Column('poa_uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('poa_uploaded_by_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'contact_id', 'role', name='uq_project_participant')
    )
    with op.batch_alter_table('project_participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_participants_contact_id'), ['contact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_participants_project_id'), ['project_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    bind = op.get_bind()
    for table in ("project_participants", "contacts"):
        count = bind.execute(sa.text(f"SELECT COUNT(*) FROM {table}")).scalar()
        if count:
            raise RuntimeError(
                f"Downgrade abgebrochen: {table} enthält {count} Zeile(n) -- Adressbuch und Beteiligte gingen "
                "verloren. Erst sichern und leeren, dann zurückrollen."
            )
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_participants_project_id'))
        batch_op.drop_index(batch_op.f('ix_project_participants_contact_id'))

    op.drop_table('project_participants')
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contacts_last_name'))
        batch_op.drop_index(batch_op.f('ix_contacts_company_name'))
        batch_op.drop_index(batch_op.f('ix_contacts_archived'))

    op.drop_table('contacts')
    # ### end Alembic commands ###
