"""Rechnungswesen

Revision ID: e057d15af828
Revises: d06425e23f3c
Create Date: 2026-09-04 08:15:16.219118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e057d15af828'
down_revision = 'd06425e23f3c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
