"""abnahme_und_gewaehrleistung -- Abnahme und Gewährleistungsdauer am Auftrag (seit 1.8.46, Stufe 2c-1)

- orders: work_kind (Leistungsart), warranty_months/warranty_days (Gewährleistungsdauer), alle leer = "nicht
  festgelegt" -- auch für den Bestand: übernommen wird nur bewusst (app/warranty.py), nie durch die Migration.
- order_warranty_changes: Historie jeder Festlegung mit dem Vorschlag dieses Zeitpunkts und ggf. Begründung.
- order_acceptances, order_acceptance_roof_areas, order_acceptance_files: Abnahmen, unveränderlich nach dem
  Speichern (app/acceptances.py); Belege als Dateien unter DACHKONZEPTE_ACCEPTANCE_FILE_ROOT.
- roof_areas.warranty_until heißt third_party_guarantee_until ("Garantie Dritter (Hersteller oder Fremdfirma)"):
  nur umbenannt, die Werte bleiben -- sie waren nie die Gewährleistung des Betriebs (die kommt jetzt aus der Abnahme).

downgrade(): bricht ab, solange etwas verloren ginge (eine Abnahme, eine Festlegung der Gewährleistung, ein Auftrag
mit Leistungsart oder Dauer); benennt die Spalte der Dachfläche zurück. Belegdateien bleiben ohnehin liegen -- die
Migration löscht keine Dateien.

Revision ID: e15280e3b567
Revises: 2798ba2fb235
Create Date: 2026-10-03 10:07:01.052124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e15280e3b567'
down_revision = '2798ba2fb235'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_acceptances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('accepted_on', sa.Date(), nullable=False),
    sa.Column('scope', sa.String(length=10), nullable=False),
    sa.Column('scope_description', sa.Text(), nullable=True),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('reservation_defects', sa.Boolean(), nullable=True),
    sa.Column('reservation_penalty', sa.Boolean(), nullable=True),
    sa.Column('contractor_objections', sa.Text(), nullable=True),
    sa.Column('declared_by', sa.String(length=20), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=True),
    sa.Column('declared_by_name', sa.String(length=255), nullable=False),
    sa.Column('declared_by_role', sa.String(length=120), nullable=True),
    sa.Column('poa_on_record', sa.Boolean(), nullable=True),
    sa.Column('conduct_reason', sa.Text(), nullable=True),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_by_name', sa.String(length=160), nullable=False),
    sa.Column('discarded_at', sa.DateTime(), nullable=True),
    sa.Column('discarded_by_user_id', sa.Integer(), nullable=True),
    sa.Column('discarded_by_name', sa.String(length=160), nullable=True),
    sa.Column('discard_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['project_participants.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_acceptances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_acceptances_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_acceptances_participant_id'), ['participant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_acceptances_property_id'), ['property_id'], unique=False)

    op.create_table('order_warranty_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('work_kind', sa.String(length=20), nullable=False),
    sa.Column('warranty_months', sa.Integer(), nullable=False),
    sa.Column('warranty_days', sa.Integer(), nullable=False),
    sa.Column('contract_basis', sa.String(length=30), nullable=False),
    sa.Column('proposal_months', sa.Integer(), nullable=False),
    sa.Column('proposal_days', sa.Integer(), nullable=False),
    sa.Column('follows_proposal', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('changed_by_name', sa.String(length=160), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_warranty_changes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_warranty_changes_order_id'), ['order_id'], unique=False)

    op.create_table('order_acceptance_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('acceptance_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['acceptance_id'], ['order_acceptances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_acceptance_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_acceptance_files_acceptance_id'), ['acceptance_id'], unique=False)

    op.create_table('order_acceptance_roof_areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('acceptance_id', sa.Integer(), nullable=False),
    sa.Column('roof_area_id', sa.Integer(), nullable=False),
    sa.Column('roof_area_name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['acceptance_id'], ['order_acceptances.id'], ),
    sa.ForeignKeyConstraint(['roof_area_id'], ['roof_areas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('acceptance_id', 'roof_area_id', name='uq_order_acceptance_roof_area')
    )
    with op.batch_alter_table('order_acceptance_roof_areas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_order_acceptance_roof_areas_acceptance_id'), ['acceptance_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_acceptance_roof_areas_roof_area_id'), ['roof_area_id'], unique=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('work_kind', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('warranty_months', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('warranty_days', sa.Integer(), nullable=True))

    # ### end Alembic commands ###
    with op.batch_alter_table('roof_areas', schema=None) as batch_op:
        batch_op.alter_column('warranty_until', new_column_name='third_party_guarantee_until',
                              existing_type=sa.Date(), existing_nullable=True)


def downgrade() -> None:
    bind = op.get_bind()
    counts = {
        "Abnahmen": bind.execute(sa.text("SELECT COUNT(*) FROM order_acceptances")).scalar(),
        "Festlegungen der Gewährleistung": bind.execute(sa.text("SELECT COUNT(*) FROM order_warranty_changes")).scalar(),
        "Aufträge mit Leistungsart oder Gewährleistungsdauer": bind.execute(sa.text(
            "SELECT COUNT(*) FROM orders WHERE work_kind IS NOT NULL OR warranty_months IS NOT NULL "
            "OR warranty_days IS NOT NULL")).scalar(),
    }
    lost = ", ".join(f"{n} {label}" for label, n in counts.items() if n)
    if lost:
        raise RuntimeError(f"Downgrade verweigert: {lost} gingen verloren.")
    with op.batch_alter_table('roof_areas', schema=None) as batch_op:
        batch_op.alter_column('third_party_guarantee_until', new_column_name='warranty_until',
                              existing_type=sa.Date(), existing_nullable=True)
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('warranty_days')
        batch_op.drop_column('warranty_months')
        batch_op.drop_column('work_kind')

    with op.batch_alter_table('order_acceptance_roof_areas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_acceptance_roof_areas_roof_area_id'))
        batch_op.drop_index(batch_op.f('ix_order_acceptance_roof_areas_acceptance_id'))

    op.drop_table('order_acceptance_roof_areas')
    with op.batch_alter_table('order_acceptance_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_acceptance_files_acceptance_id'))

    op.drop_table('order_acceptance_files')
    with op.batch_alter_table('order_warranty_changes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_warranty_changes_order_id'))

    op.drop_table('order_warranty_changes')
    with op.batch_alter_table('order_acceptances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_acceptances_property_id'))
        batch_op.drop_index(batch_op.f('ix_order_acceptances_participant_id'))
        batch_op.drop_index(batch_op.f('ix_order_acceptances_order_id'))

    op.drop_table('order_acceptances')
    # ### end Alembic commands ###
