"""E-Mail-Versand: SMTP-Einstellungen und Mahnstufen-Textbausteine

Revision ID: e52a06d5ff38
Revises: 53778598ef1d
Create Date: 2026-09-07 08:50:53.445051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e52a06d5ff38'
down_revision = '53778598ef1d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('smtp_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=True),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('password_encrypted', sa.Text(), nullable=True),
    sa.Column('encryption', sa.String(length=20), nullable=False),
    sa.Column('sender_email', sa.String(length=255), nullable=True),
    sa.Column('sender_name', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reminder_levels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_subject_template', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('email_body_template', sa.Text(), nullable=True))

    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_sent_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('email_sent_to', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminders', schema=None) as batch_op:
        batch_op.drop_column('email_sent_to')
        batch_op.drop_column('email_sent_at')

    with op.batch_alter_table('reminder_levels', schema=None) as batch_op:
        batch_op.drop_column('email_body_template')
        batch_op.drop_column('email_subject_template')

    op.drop_table('smtp_settings')
    # ### end Alembic commands ###
