"""outlook series occurrences

Revision ID: ea1034dc38e7
Revises: 1375eeeea2fa
Create Date: 2026-09-28 16:40:00.911142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea1034dc38e7'
down_revision = '1375eeeea2fa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outlook_series_occurrences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('outlook_event_id', sa.String(length=255), nullable=False),
    sa.Column('series_master_id', sa.String(length=255), nullable=True),
    sa.Column('occurrence_type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('start_at', sa.DateTime(), nullable=False),
    sa.Column('end_at', sa.DateTime(), nullable=False),
    sa.Column('all_day', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_private', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('outlook_etag', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['app_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_user_id', 'outlook_event_id', name='uq_outlook_series_occurrence_owner_event')
    )
    with op.batch_alter_table('outlook_series_occurrences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outlook_series_occurrences_end_at'), ['end_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_outlook_series_occurrences_owner_user_id'), ['owner_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outlook_series_occurrences_start_at'), ['start_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outlook_series_occurrences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outlook_series_occurrences_start_at'))
        batch_op.drop_index(batch_op.f('ix_outlook_series_occurrences_owner_user_id'))
        batch_op.drop_index(batch_op.f('ix_outlook_series_occurrences_end_at'))

    op.drop_table('outlook_series_occurrences')
    # ### end Alembic commands ###
