"""document_layout_backgrounds: page_type je Seitentyp

Revision ID: ec3120ba11cf
Revises: a1b7a145e5d5
Create Date: 2026-09-10 17:43:08.131386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec3120ba11cf'
down_revision = 'a1b7a145e5d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_layout_backgrounds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('page_type', sa.String(length=20), server_default='first', nullable=False))
        batch_op.drop_index(batch_op.f('ix_document_layout_backgrounds_document_type'))
        batch_op.create_index(batch_op.f('ix_document_layout_backgrounds_document_type'), ['document_type'], unique=False)
        batch_op.create_unique_constraint('uq_document_layout_background_type_page', ['document_type', 'page_type'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_layout_backgrounds', schema=None) as batch_op:
        batch_op.drop_constraint('uq_document_layout_background_type_page', type_='unique')
        batch_op.drop_index(batch_op.f('ix_document_layout_backgrounds_document_type'))
        batch_op.create_index(batch_op.f('ix_document_layout_backgrounds_document_type'), ['document_type'], unique=1)
        batch_op.drop_column('page_type')

    # ### end Alembic commands ###
