"""operational assets erweiterungen faelligkeit dokumente

Revision ID: ed896599a211
Revises: ccb5c4c0915b
Create Date: 2026-09-17 22:24:16.848988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed896599a211'
down_revision = 'ccb5c4c0915b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operational_asset_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=80), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['operational_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('operational_asset_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operational_asset_documents_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_operational_asset_documents_document_type'), ['document_type'], unique=False)

    with op.batch_alter_table('operational_asset_inspections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_reminder_due_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operational_asset_inspections', schema=None) as batch_op:
        batch_op.drop_column('last_reminder_due_date')

    with op.batch_alter_table('operational_asset_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operational_asset_documents_document_type'))
        batch_op.drop_index(batch_op.f('ix_operational_asset_documents_asset_id'))

    op.drop_table('operational_asset_documents')
    # ### end Alembic commands ###
