"""asset recurring cost quick entry link

Revision ID: eda89bb8082a
Revises: 9b3600be64af
Create Date: 2026-09-19 12:32:40.662288

Nachbesserung "Betriebsmittel-Kosten fest als Kostenposten" (siehe CLAUDE.md): löst die
1.5.0-Doppelzählungs-Sonderbehandlung ab -- RecurringCost ist seither die einzige Quelle für
Betriebsmittel-Kosten, kein zweites, paralleles Feld mehr auf OperationalAsset selbst.

operational_assets.recurring_cost_per_month wird entfernt -- gegen die echte, lokale Datenbank
geprüft: 0 Zeilen trugen einen Wert (siehe Befund im Chatverlauf), die Migration braucht deshalb
keinen Datenbackfill, nur den Spaltenabbau selbst.

recurring_costs.is_asset_quick_entry (neu, NOT NULL, server_default='0' -- Regel 1) markiert den
einen Kostenposten je Betriebsmittel, der vom "Laufende Kosten je Monat"-Feld des
Betriebsmittel-Formulars verwaltet wird -- siehe RecurringCost-Klassendocstring (app/models.py)
und app/operational_assets.py::sync_asset_recurring_cost() für die volle Begründung, warum das
eine reine Anwendungs-Invariante ist, kein DB-Constraint."""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eda89bb8082a'
down_revision = '9b3600be64af'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operational_assets', schema=None) as batch_op:
        batch_op.drop_column('recurring_cost_per_month')

    with op.batch_alter_table('recurring_costs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_asset_quick_entry', sa.Boolean(), server_default='0', nullable=False))
        batch_op.create_index(batch_op.f('ix_recurring_costs_is_asset_quick_entry'), ['is_asset_quick_entry'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recurring_costs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recurring_costs_is_asset_quick_entry'))
        batch_op.drop_column('is_asset_quick_entry')

    with op.batch_alter_table('operational_assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recurring_cost_per_month', sa.NUMERIC(precision=12, scale=2), nullable=True))

    # ### end Alembic commands ###
