"""service_report_materials

Revision ID: f6f429b505f3
Revises: 06299a5101f5
Create Date: 2026-09-10 14:50:05.430480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6f429b505f3'
down_revision = '06299a5101f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_report_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_report_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('roof_area_id', sa.Integer(), nullable=True),
    sa.Column('inspection_item_id', sa.Integer(), nullable=True),
    sa.Column('finding_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='100', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_employee_id', sa.Integer(), nullable=True),
    sa.Column('client_uuid', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['created_by_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ),
    sa.ForeignKeyConstraint(['inspection_item_id'], ['inspection_items.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['roof_area_id'], ['roof_areas.id'], ),
    sa.ForeignKeyConstraint(['service_report_id'], ['service_reports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_report_id', 'client_uuid', name='uq_service_report_material_client_uuid')
    )
    with op.batch_alter_table('service_report_materials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_report_materials_client_uuid'), ['client_uuid'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_report_materials_finding_id'), ['finding_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_report_materials_inspection_item_id'), ['inspection_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_report_materials_material_id'), ['material_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_report_materials_roof_area_id'), ['roof_area_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_report_materials_service_report_id'), ['service_report_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_report_materials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_report_materials_service_report_id'))
        batch_op.drop_index(batch_op.f('ix_service_report_materials_roof_area_id'))
        batch_op.drop_index(batch_op.f('ix_service_report_materials_material_id'))
        batch_op.drop_index(batch_op.f('ix_service_report_materials_inspection_item_id'))
        batch_op.drop_index(batch_op.f('ix_service_report_materials_finding_id'))
        batch_op.drop_index(batch_op.f('ix_service_report_materials_client_uuid'))

    op.drop_table('service_report_materials')
    # ### end Alembic commands ###
