"""property documents table

Revision ID: f803985ebc2f
Revises: 9137945e8785
Create Date: 2026-09-16 13:24:57.218932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f803985ebc2f'
down_revision = '9137945e8785'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=150), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('uploaded_by_employee_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['document_categories.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_filename')
    )
    with op.batch_alter_table('property_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_property_documents_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_property_documents_property_id'), ['property_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_property_documents_uploaded_at'), ['uploaded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_property_documents_uploaded_by_employee_id'), ['uploaded_by_employee_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_property_documents_uploaded_by_employee_id'))
        batch_op.drop_index(batch_op.f('ix_property_documents_uploaded_at'))
        batch_op.drop_index(batch_op.f('ix_property_documents_property_id'))
        batch_op.drop_index(batch_op.f('ix_property_documents_category_id'))

    op.drop_table('property_documents')
    # ### end Alembic commands ###
