"""add maintenance contracts table

Revision ID: f866cb9b23e7
Revises: 6ed174efcf4a
Create Date: 2026-09-08 16:27:14.164519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f866cb9b23e7'
down_revision = '6ed174efcf4a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('interval_months', sa.Integer(), nullable=False),
    sa.Column('next_due_date', sa.Date(), nullable=False),
    sa.Column('last_reminder_due_date', sa.Date(), nullable=True),
    sa.Column('template_project_id', sa.Integer(), nullable=True),
    sa.Column('responsible_employee_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), server_default='aktiv', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['responsible_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['template_project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('maintenance_contracts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maintenance_contracts_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_maintenance_contracts_property_id'), ['property_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_contracts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maintenance_contracts_property_id'))
        batch_op.drop_index(batch_op.f('ix_maintenance_contracts_customer_id'))

    op.drop_table('maintenance_contracts')
    # ### end Alembic commands ###
