"""time tracking lock

Revision ID: fa2105afb89a
Revises: ea1034dc38e7
Create Date: 2026-09-29 08:49:25.970177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa2105afb89a'
down_revision = 'ea1034dc38e7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_tracking_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('locked_until', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('locked_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('locked_by_user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_time_tracking_settings_locked_by_user_id', 'app_users', ['locked_by_user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_tracking_settings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_time_tracking_settings_locked_by_user_id', type_='foreignkey')
        batch_op.drop_column('locked_by_user_id')
        batch_op.drop_column('locked_at')
        batch_op.drop_column('locked_until')

    # ### end Alembic commands ###
