"""recurring costs betriebskosten uebersicht

Revision ID: fc79aa5629d0
Revises: 7677d9d878ba
Create Date: 2026-09-18 14:49:08.573057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc79aa5629d0'
down_revision = '7677d9d878ba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_cost_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reminder_lead_days', sa.Integer(), server_default='30', nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recurring_costs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('billing_interval', sa.String(length=20), nullable=False),
    sa.Column('annual_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('vendor', sa.String(length=255), nullable=True),
    sa.Column('contract_end_date', sa.Date(), nullable=True),
    sa.Column('notice_period_months', sa.Integer(), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('last_reminder_due_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['operational_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recurring_costs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recurring_costs_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_recurring_costs_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recurring_costs_category'), ['category'], unique=False)

    op.create_table('recurring_cost_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recurring_cost_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=80), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recurring_cost_id'], ['recurring_costs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recurring_cost_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recurring_cost_documents_document_type'), ['document_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_recurring_cost_documents_recurring_cost_id'), ['recurring_cost_id'], unique=False)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_visible_role', sa.String(length=30), nullable=True))
        batch_op.create_index(batch_op.f('ix_tasks_min_visible_role'), ['min_visible_role'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_min_visible_role'))
        batch_op.drop_column('min_visible_role')

    with op.batch_alter_table('recurring_cost_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recurring_cost_documents_recurring_cost_id'))
        batch_op.drop_index(batch_op.f('ix_recurring_cost_documents_document_type'))

    op.drop_table('recurring_cost_documents')
    with op.batch_alter_table('recurring_costs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recurring_costs_category'))
        batch_op.drop_index(batch_op.f('ix_recurring_costs_asset_id'))
        batch_op.drop_index(batch_op.f('ix_recurring_costs_active'))

    op.drop_table('recurring_costs')
    op.drop_table('recurring_cost_settings')
    # ### end Alembic commands ###
