"""incoming invoices buchhaltung stufe 1

Revision ID: fd1cc820d6b7
Revises: 0f7bda3397f1
Create Date: 2026-09-21 17:48:12.222102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd1cc820d6b7'
down_revision = '0f7bda3397f1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incoming_invoice_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skonto_reminder_lead_days', sa.Integer(), server_default='5', nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incoming_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('supplier_invoice_number', sa.String(length=80), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_rate_pct', sa.Numeric(precision=5, scale=2), server_default='19.00', nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('skonto_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('skonto_deadline', sa.Date(), nullable=True),
    sa.Column('payment_status', sa.String(length=20), server_default='offen', nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('document_filename', sa.String(length=255), nullable=True),
    sa.Column('document_original_name', sa.String(length=255), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('recurring_cost_id', sa.Integer(), nullable=True),
    sa.Column('account_code', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('last_skonto_reminder_deadline', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['operational_assets.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['recurring_cost_id'], ['recurring_costs.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incoming_invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incoming_invoices_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incoming_invoices_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_incoming_invoices_invoice_date'), ['invoice_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_incoming_invoices_payment_status'), ['payment_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_incoming_invoices_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incoming_invoices_recurring_cost_id'), ['recurring_cost_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incoming_invoices_skonto_deadline'), ['skonto_deadline'], unique=False)
        batch_op.create_index(batch_op.f('ix_incoming_invoices_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('incoming_invoice_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incoming_invoice_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_rate_pct', sa.Numeric(precision=5, scale=2), server_default='19.00', nullable=False),
    sa.Column('account_code', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['incoming_invoice_id'], ['incoming_invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incoming_invoice_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incoming_invoice_items_incoming_invoice_id'), ['incoming_invoice_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incoming_invoice_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incoming_invoice_items_incoming_invoice_id'))

    op.drop_table('incoming_invoice_items')
    with op.batch_alter_table('incoming_invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incoming_invoices_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_incoming_invoices_skonto_deadline'))
        batch_op.drop_index(batch_op.f('ix_incoming_invoices_recurring_cost_id'))
        batch_op.drop_index(batch_op.f('ix_incoming_invoices_project_id'))
        batch_op.drop_index(batch_op.f('ix_incoming_invoices_payment_status'))
        batch_op.drop_index(batch_op.f('ix_incoming_invoices_invoice_date'))
        batch_op.drop_index(batch_op.f('ix_incoming_invoices_due_date'))
        batch_op.drop_index(batch_op.f('ix_incoming_invoices_asset_id'))

    op.drop_table('incoming_invoices')
    op.drop_table('incoming_invoice_settings')
    # ### end Alembic commands ###
