"""Konfigurierbare Tabellenfelder (Meta, Summen, Positionsliste)

Revision ID: fff4d8ae8433
Revises: 9e959412c279
Create Date: 2026-09-05 10:57:19.791211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fff4d8ae8433'
down_revision = '9e959412c279'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_table_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=20), nullable=False),
    sa.Column('block_type', sa.String(length=30), nullable=False),
    sa.Column('field_key', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.Column('custom_value', sa.Text(), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_table_fields', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_table_fields_block_type'), ['block_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_table_fields_document_type'), ['document_type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_table_fields', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_table_fields_document_type'))
        batch_op.drop_index(batch_op.f('ix_document_table_fields_block_type'))

    op.drop_table('document_table_fields')
    # ### end Alembic commands ###
